Feat cruds
platanus/2021-1-Grupo4-Web pull request #10
Opened 2021-04-20 15:07 UTC by fthurtado

2021-04-20 16:02 UTC, fthurtado commented
Se crean las migraciones, modelos y factories correspondientes a cada crud. Específicamente de,
1. Ingredients
2. Recipes
3. RecipeIngredients
4. Menus
5. Providers

A nivel de código habría que revisar
- [ ] Relaciones entre modelos
- [ ] Nombres y tipos correctos de atributos

## QA

- Correr las migraciones y luego correr la app
  -  Debería correr todo bien

2021-04-20 22:01 UTC, cacosandon commented on package.json
> +    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.1.0",
no sé si está bien que esto se haya subido, porque estaba todo funcionando perfect con respecto a esto

hiciste `yarn install` en local? si lo hiciste, haría un rebase para asegurarme

2021-04-20 22:01 UTC, cacosandon commented on spec/requests/ingredients_spec.rb
> +      expect(response).to have_http_status(:success)
seguramente falla por esto
```suggestion
      get "/ingredients/"
      expect(response).to have_http_status(:success)
```

2021-04-20 22:02 UTC, cacosandon commented on spec/requests/recipes_spec.rb
> +    pending "add some examples (or delete) #{__FILE__}"
lo mismo acá

2021-04-20 22:03 UTC, cacosandon requested changes
dejé varios comentarios, y otros:

- será mejor dejar SKU como sku?
- faltan tests de asociaciones! 
- se rompió algo con tailwind, dejé un comentario

2021-04-21 01:13 UTC, iaacosta requested changes
Buena :rocket:! Te dejé unos comentarios, aparte te dejo otros más generales:

- [Se te pasó un `.DS_Store`](https://github.com/platanus/2021-1-Grupo4-Web/blob/32b7e61753aecc97ac7ea2d8b376bb9a9b1b5f80/.DS_Store)
- Haciendo `rails db:migrate` en local me agrego anotaciones a varios modelos y me cambió el `schema.rb`, para que lo re-ejecutes y quede como parte de este PR
- Si quieres, échale una mirada a [este post](https://blog.platan.us/manteniendo-la-historia-limpia-usando-git-rebase-5cceecd5367a) que escribió Rai, explica a grandes rasgos cómo usar `git rebase`. Sirve harto cuando tienes hartos commits de "fix" o "refactor" de la misma PR, así se facilita la revisión (cada commit lleva algo terminado)
- Como dijo @cacosandon, faltan los tests de las asociaciones! Te recomiendo usar [`shoulda-matchers`](https://github.com/thoughtbot/shoulda-matchers) para hacerlos, es buena herramienta y quedan simples de leer y escribir. Por ejemplo, [este](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matcher.rb#L328) sirve para hacer tests de asociaciones de `has_many` (las instrucciones están en el código comentado)

Asumiendo que las validaciones de atributos las harán en otra PR, veo bien el resto 👏🏻

2021-04-21 01:13 UTC, iaacosta commented on spec/requests/ingredients_spec.rb
> +      expect(response).to have_http_status(:success)
Creo que falla porque no hay rutas ni controladores de ingredientes 👀, lo mismo con todos los _specs_ que están en `spec/requests/`, yo los borraría si aun no están implementados.

2021-04-21 19:41 UTC, monkeyci commented on app/models/menu.rb
> +  has_many :recipes
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasManyOrHasOneDependent: Specify a :dependent option.

2021-04-21 19:41 UTC, monkeyci commented on app/models/provider.rb
> +    has_many :ingredients, dependent: :destroy
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2021-04-21 19:41 UTC, monkeyci commented on app/models/user.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-21 19:41 UTC, monkeyci commented on spec/requests/ingredients_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.

2021-04-21 19:41 UTC, monkeyci commented on spec/requests/providers_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.

2021-04-21 21:26 UTC, monkeyci commented on app/models/menu_recipe.rb
> +    belongs_to :recipe
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2021-04-21 21:26 UTC, monkeyci commented on app/models/menu_recipe.rb
> +    belongs_to :menu
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2021-04-21 21:26 UTC, monkeyci commented on spec/factories/menu_recipes.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-21 21:39 UTC, Arodriguez14 commented on package.json
> +    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.1.0",
Hicimos el rebase. Gracias!

2021-04-21 21:40 UTC, Arodriguez14 commented on spec/requests/ingredients_spec.rb
> +      expect(response).to have_http_status(:success)
Perfecto. Los borramos por ahora. Gracias!

2021-04-21 21:40 UTC, Arodriguez14 commented on spec/requests/recipes_spec.rb
> +    pending "add some examples (or delete) #{__FILE__}"
Perfecto! Lo borramos por ahora. Gracias

2021-04-21 21:42 UTC, Arodriguez14 commented on app/models/ingredient.rb
> +  belongs_to :provider
Buenísimo. Muchas gracias. Quedan pendiente las validaciones de las asociaciones para la próxima PR

2021-04-21 21:42 UTC, Arodriguez14 commented on app/models/menu.rb
> +  has_many :recipes
No sabíamos que había que declarar siempre un dependant. Ya esta ok! Gracias

2021-04-21 21:43 UTC, Arodriguez14 commented on db/migrate/20210416213909_create_ingredients.rb
> +      t.integer :user_id
Perfect. Así lo hicimos. Gracias por la ayuda!

2021-04-22 13:30 UTC, iaacosta reviewed
Buena, quedó mucho mejor!

No caché porque te salieron 80 commits 😅 algo debió haber pasado ahí con el rebase.

Me queda la duda de si harán tests de modelo 👀

2021-04-22 16:40 UTC, fthurtado commented
> Buena, quedó mucho mejor!
> 
> No caché porque te salieron 80 commits 😅 algo debió haber pasado ahí con el rebase.
> 
> Me queda la duda de si harán tests de modelo 👀

Buenísimo!

Sí, ahí voy a ver bien que pasó con el rebase 😬.

Si los haremos! Hoy día los deberíamos empezar.

2021-04-22 16:41 UTC, iaacosta commented
> > Buena, quedó mucho mejor!
> > No caché porque te salieron 80 commits 😅 algo debió haber pasado ahí con el rebase.
> > Me queda la duda de si harán tests de modelo 👀
> 
> Buenísimo!
> 
> Sí, ahí voy a ver bien que pasó con el rebase 😬.
> 
> Si los haremos! Hoy día los deberíamos empezar.

Bacán! Avísame si serán en esta PR u otra para aprobar 👍🏻

2021-04-22 16:42 UTC, fthurtado commented
> > > Buena, quedó mucho mejor!
> > > No caché porque te salieron 80 commits 😅 algo debió haber pasado ahí con el rebase.
> > > Me queda la duda de si harán tests de modelo 👀
> > 
> > 
> > Buenísimo!
> > Sí, ahí voy a ver bien que pasó con el rebase 😬.
> > Si los haremos! Hoy día los deberíamos empezar.
> 
> Bacán! Avísame si serán en esta PR u otra para aprobar 👍🏻

En esta misma!

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +  let(:subject) { create(:provider) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterFinalLet: Add an empty line after the last let.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    it "should include the :id attribute" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExampleWording: Do not use should when describing your tests.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +      expect(subject.attributes).to include("id")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    it "should include the :name attribute" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExampleWording: Do not use should when describing your tests.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +      expect(subject.attributes).to include("name")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    it "should include the :address attribute" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExampleWording: Do not use should when describing your tests.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +      expect(subject.attributes).to include("address")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    it "should include the :country attribute" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ExampleWording: Do not use should when describing your tests.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +      expect(subject.attributes).to include("country")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-22 20:34 UTC, monkeyci commented on spec/models/provider_spec.rb
> +    it { should have_many(:ingredients) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ImplicitExpect: Prefer is_expected.to over should.

2021-04-22 20:38 UTC, monkeyci commented on spec/factories/ingredients.rb
> +    price { rand(50..300)*10 }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/SpaceAroundOperators: Surrounding space missing for operator *.

2021-04-24 18:23 UTC, fncabrera requested changes
- Les arreglé los errores autofixable de rubocop (ojo con siempre correr rubocop antes de crear la PR)
- Hay test que están fallando para que los revisen (recuerden tb antes de crear la PR, probar que en local estén funcionando bien
- No logro cachar porque hay ciertos warnings de rubocop que salen acá y no en local (los de rspec). Estaba viendo la file de .rubocop.yml y no cacho porque localmente está ignorando algunos). Se te ocurre @cacosandon o alguien de 🍌 ?

2021-04-24 19:28 UTC, iaacosta commented
> * No logro cachar porque hay ciertos warnings de rubocop que salen acá y no en local (los de rspec). Estaba viendo la file de .rubocop.yml y no cacho porque localmente está ignorando algunos). Se te ocurre @cacosandon o alguien de 🍌 ?

Quizás es por como lo están ejecutando. Si usan `rubocop` a secas, quizás no están usando la misma versión o archivos de reglas. Se pueden ir a la segura con `bundle exec rubocop`, que si respeta todo eso (lo probé en local y no tuve problemas).

Si siguen con problemas, acá pueden ver exactamente como el CI ejecuta `rubocop`, que solo agrega la complejidad extra de filtrar los archivos cambiados en la PR para no alegar por lint errores que no les corresponde a estos cambios.

Avísenme cualquier duda!

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +  describe MenuRecipe do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [8]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +    subject(:menu_recipe) { build(:menu_recipe) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterSubject: Add an empty line after subject.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +  describe MenuRecipe do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [4]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +    subject(:menu_recipe) { build(:menu_recipe) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterSubject: Add an empty line after subject.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +      expect(subject.attributes).to include("id")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_recipe_spec.rb
> +      expect(subject.attributes).to include("recipe_quantity")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +  describe Menu do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [19]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +    subject(:menu) { build(:menu) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterSubject: Add an empty line after subject.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +      expect(subject.attributes).to include("id")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +      expect(subject.attributes).to include("name")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +  describe Menu do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [4]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/menu_spec.rb
> +    it { should have_many(:recipes).through(:menu_recipes) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/ImplicitExpect: Prefer is_expected.to over should.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +  describe RecipeIngredient do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [8]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +    subject(:recipe_ingredient) { build(:recipe_ingredient) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterSubject: Add an empty line after subject.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +  describe RecipeIngredient do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/RepeatedExampleGroupDescription: Repeated describe block description on line(s) [4]

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +    subject(:recipe_ingredient) { build(:recipe_ingredient) }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterSubject: Add an empty line after subject.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +  end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +      expect(subject.attributes).to include("id")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +    end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] RSpec/EmptyLineAfterExample: Add an empty line after it.

2021-04-25 17:09 UTC, monkeyci commented on spec/models/recipe_ingredient_spec.rb
> +      expect(subject.attributes).to include("ingredient_quantity")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/NamedSubject: Name your test subject if you need to reference it explicitly.

2021-04-25 22:22 UTC, fthurtado commented
Todos los test de modelos listos en último commit.

Quedo atento a sus comentarios para poder pasar la PR 😄 (sé que es domingo, así que lo espero para la semana)

Muchas gracias!!

2021-04-26 16:21 UTC, iaacosta requested changes
Quedaron buenos los tests 👍🏻 Te puse un par de comentarios más DRY y de otros tests que quizás no son tan necesarios, cuéntame que opinas.

Traté de revisar a la rápida qué onda los 80+ commits, pero no se me ocurre cómo arreglarlo fácil. Podrías probar [haciendo `rebase` y `squash`](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together) para tener menos si quieres, pero me tinca que te van a salir hartos conflictos.

2021-04-26 16:21 UTC, iaacosta commented on spec/models/ingredient_spec.rb
> +    end
Buena! Creo que se puede mejorar con esto:

```suggestion
    ["name", "sku", "price", "currency", "quantity", "measure"].each do |attribute|
      it "includes the #{attribute} attribute" do
        expect(ingredient.attributes).to include(attribute)
      end
    end
```

No incluí `id` porque no creo que sea necesario testearlo por ser default en todos los modelos de Rails.

2021-04-26 16:21 UTC, iaacosta commented on spec/models/menu_recipe_spec.rb
> +    end
Lo sacaría por lo mismo que te dije arriba!

2021-04-26 16:21 UTC, iaacosta commented on spec/models/menu_spec.rb
> +    end
Ídem

2021-04-26 16:21 UTC, iaacosta commented on spec/models/provider_spec.rb
> +    end
Ídem

2021-04-26 16:21 UTC, iaacosta commented on spec/models/provider_spec.rb
> +    end
```suggestion
    ["name", "address", "country"].each do |attribute|
      it "includes the :#{attribute} attribute" do
        expect(provider.attributes).to include(attribute)
      end
    end
```

2021-04-26 16:21 UTC, iaacosta commented on spec/models/recipe_ingredient_spec.rb
> +    end
Ídem

2021-04-26 16:21 UTC, iaacosta commented on spec/models/recipe_spec.rb
> +    end
Ídem

2021-04-26 16:21 UTC, iaacosta commented on spec/models/recipe_spec.rb
> +    end
```suggestion
    ["name", "portions", "instructions", "cook_minutes"].each do |attribute|
      it "includes the #{attribute} attribute" do
        expect(recipe.attributes).to include(attribute)
      end
    end
```

2021-04-26 16:21 UTC, iaacosta commented on spec/models/user_spec.rb
> +    end
Estos los sacaría porque en rigor son responsabilidad de `devise`.

El de `authentication_token` lo agregaron ustedes y encuentro que está bien que lo testeen.

2021-04-26 16:29 UTC, monkeyci commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/FilePath: Please use Rails.root.join('path/to') instead.

2021-04-26 16:29 UTC, monkeyci commented on spec/swagger_helper.rb
> +  config.swagger_root = "#{Rails.root}/swagger"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/FilePath: Please use Rails.root.join('path/to') instead.

2021-04-26 17:01 UTC, monkeyci commented on spec/rails_helper.rb
> +# This file is copied to spec/ when you run 'rails generate rspec:install'
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/EndOfLine: Carriage return character detected.

2021-04-26 17:01 UTC, monkeyci commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Lint/NonDeterministicRequireOrder: Sort files before requiring them.

2021-04-26 17:01 UTC, monkeyci commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/FilePath: Please use Rails.root.join('path/to') instead.

2021-04-26 17:01 UTC, monkeyci commented on spec/swagger_helper.rb
> +require 'rails_helper'
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/EndOfLine: Carriage return character detected.

2021-04-26 17:01 UTC, monkeyci commented on spec/swagger_helper.rb
> +Dir[::Rails.root.join("spec/swagger/**/schemas/*.rb")].each { |f| require f }
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Lint/NonDeterministicRequireOrder: Sort files before requiring them.

2021-04-26 17:01 UTC, monkeyci commented on spec/swagger_helper.rb
> +Dir[::Rails.root.join("spec/swagger/**/definition.rb")].each { |f| require f }
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Lint/NonDeterministicRequireOrder: Sort files before requiring them.

2021-04-26 17:01 UTC, monkeyci commented on spec/swagger_helper.rb
> +  config.swagger_root = Rails.root.to_s + '/swagger'
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/StringConcatenation: Prefer string interpolation to string concatenation.

2021-04-26 17:55 UTC, fncabrera approved these changes
QA good, ojo con los cambios y sugerencias en tests!

Pd sorry por agregarles más commits jajaja me mandé un cagazo arreglando temas de rubocop pero quedo 👌

2021-04-26 20:08 UTC, fthurtado commented on spec/models/ingredient_spec.rb
> +    end
Me parece!

2021-04-26 20:09 UTC, fthurtado commented on spec/models/user_spec.rb
> +    end
Perfecto!

2021-04-26 20:10 UTC, iaacosta approved these changes
Buena pega 👏🏻

2021-04-26 21:55 UTC, miortiz1 commented
Me equivoque con un commit de un merge, lo voy a arreglar al tiro, para que no lo revisen por ahora.

2021-04-27 23:10 UTC, cacosandon approved these changes

2021-04-27 23:10 UTC, merged