feat(menus): add shopping list to menu
platanus/2021-1-Grupo4-Web pull request #103
Opened 2021-06-12 18:03 UTC by cacosandon

BASE [#70] (cambio en las measures)

Card https://trello.com/c/NbH10C37/9-generar-lista-de-compras

#### Contexto
Actualmente el menú tiene recetas (puede 5 pasteles de choclo) y cada receta tiene muchos ingredientes (además puede tener 5 choclos). Cada ingrediente tiene una medida por default (la primera de todas las que tiene)

#### Qué hice
- Modifiqué el spinner para que sea tamaño por default, ahora el loading se puede usar en cualquier parte más bonito y el wrapper se hace afuera
- Creo el backend y frontend web para ver la lista de compras de un menú.

Ahora el spinner el buscar en ingredientes:

https://user-images.githubusercontent.com/30879716/121785231-8d344000-cb86-11eb-9af3-8fda6c08517b.mov

La lista de compras de cada menú (no se ve el spinner porque está muy rápido :hyper-fast-parrot:):

https://user-images.githubusercontent.com/30879716/121785253-c2409280-cb86-11eb-8d79-dd6a48a5db86.mov

2021-06-13 23:01 UTC, ValentinaAlvarezG requested changes
- Algo anda mal con el index de recetas. Cuando creo una, si bien se agregan a la bd (porque en menús me aparecen esas recetas) en el index de recetas no se están mostrando.
- Creo que algo anda mal con los precios, entonces me sale que el precio de un menú es infinito y por lo tanto cuando agrego el menú al "carro" no puedo comprobar que los precios estén bien ya me que sale 0 null, $0
![image](https://user-images.githubusercontent.com/26123660/121824335-82a6a300-cc79-11eb-926e-fb1c1a79cf4e.png)
![image](https://user-images.githubusercontent.com/26123660/121824346-9ce08100-cc79-11eb-86a7-678dcacc2189.png)

2021-06-13 23:32 UTC, cacosandon commented
> * Algo anda mal con el index de recetas. Cuando creo una, si bien se agregan a la bd (porque en menús me aparecen esas recetas) en el index de recetas no se están mostrando.
> * Creo que algo anda mal con los precios, entonces me sale que el precio de un menú es infinito y por lo tanto cuando agrego el menú al "carro" no puedo comprobar que los precios estén bien ya me que sale 0 null, $0
>   ![image](https://user-images.githubusercontent.com/26123660/121824335-82a6a300-cc79-11eb-926e-fb1c1a79cf4e.png)
>   ![image](https://user-images.githubusercontent.com/26123660/121824346-9ce08100-cc79-11eb-86a7-678dcacc2189.png)

faltaba un rebase creo! ahora me funca

2021-06-13 23:51 UTC, ValentinaAlvarezG approved these changes
Bacan! todo bien ahora. Eventualmente quizás le haría un pequeño cambio de diseño al modal que  te muestra los ingredientes. Quizás en una tabla para que se vea más ordenada la información en vez de separada por comas, además de mostrar el precio final por proveedor quizás (pero detalles para otra PR)

2021-06-15 01:09 UTC, agomezcampero approved these changes
Lo veo bien, perdón lo tarde no me aviso el bot y lo acabo de ver en mi email

2021-06-15 01:09 UTC, agomezcampero commented on app/javascript/components/menus/index/menu-shopping-list.vue
> +    },
algo que es un poco más simple que esto es redirigir al usuario a la ruta que devuelve el xlsx directo, es tarde y mñna presentan asique si están apurados no se preocupen

2021-06-15 01:10 UTC, fthurtado approved these changes

2021-06-15 01:10 UTC, cacosandon commented on app/javascript/components/menus/index/menu-shopping-list.vue
> +    },
oh verdad jaja, no lo había pensao
lo haré así mejor altiro 👍

2021-06-15 01:20 UTC, cacosandon commented on app/javascript/components/menus/index/menu-shopping-list.vue
> +    },
ready!

2021-06-15 01:37 UTC, merged