feat(shopping-list): add download xlsx
platanus/2021-1-Grupo4-Web pull request #105
Opened 2021-06-12 23:03 UTC by cacosandon

Continuación [#103]

Agrego que se pueda descargar la lista de compra de ese menú mediante un excel

https://user-images.githubusercontent.com/30879716/121790744-760a4800-cbb0-11eb-85e2-42bd0d13815f.mov

2021-06-14 14:32 UTC, difernandez requested changes

2021-06-14 14:32 UTC, difernandez commented on app/javascript/components/menus/index/menu-shopping-list.vue
> +    async toogleList() {
Mini typo: *toggle

2021-06-14 21:26 UTC, cacosandon commented on app/javascript/components/menus/index/menu-shopping-list.vue
> +    async toogleList() {
oops

2021-06-14 21:27 UTC, difernandez approved these changes

2021-06-15 00:18 UTC, fthurtado approved these changes
Se ve todo ok, y funciona 👌

2021-06-15 00:25 UTC, merged