Ingredient measure
platanus/2021-1-Grupo4-Web pull request #108
Opened 2021-06-13 01:17 UTC by miortiz1

## Que se hizo
Al crear o editar la medida de un ingrediente en una receta queda guardado en bd.
## QA
Crear una receta y seleccionar medidas para sus ingredientes. Luego al editarla se cargue mostrando las medidas correctas. Al guardar cambios se debe ver reflejado en el show

2021-06-13 01:28 UTC, rjherrera reviewed
buena, tuviste suerte de que estaba en el computador jajaa, me quedaron dos dudas chicas pero se ve bien!

2021-06-13 01:28 UTC, rjherrera commented on db/schema.rb
> -  create_table "ingredient_measures", force: :cascade do |t|
no caché bien que pasó acá, no veo una migración y veo que se elimina esta tabla 🤔

2021-06-13 01:28 UTC, rjherrera commented on app/javascript/components/recipes/base/selected-ingredient-card.vue
> +        ingredientUnits.unshift(this.recipeIngredientAttrs.ingredientMeasure);
no entiendo muy bien esta lógica, por lo que veo modificas el arreglo ingredientUnits para que ahora se quede solo con los items que son distintos del measure y después agregas el measure al principio, cuál es el objetivo? asegurarte que siempre esté el measure pero que no se repita? algo así?

Lo pregunto porque si te da lo mismo que hayan repetidos, sería llegar y agregarlo, no habría que hacer ese filter primero.

2021-06-13 02:28 UTC, miortiz1 commented on app/javascript/components/recipes/base/selected-ingredient-card.vue
> +        ingredientUnits.unshift(this.recipeIngredientAttrs.ingredientMeasure);
En verdad lo que busco aca es que si el ingrediente tiene una medida que esta quede al principio del arreglo de sus medidas.

2021-06-13 02:30 UTC, monkeyci commented on app/controllers/api/v1/recipes_controller.rb
> +    binding.pry
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Lint/Debugger: Remove debugger entry point binding.pry.

2021-06-13 02:30 UTC, monkeyci commented on app/javascript/components/ingredients/ingredients-container.vue
> +        console.log(ingredientsInfo);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-06-13 02:31 UTC, miortiz1 commented on db/schema.rb
> -  create_table "ingredient_measures", force: :cascade do |t|
Esta más abajo la misma tabla, no se que habrá pasado :thinking:

2021-06-13 02:35 UTC, rjherrera commented on app/javascript/components/recipes/base/selected-ingredient-card.vue
> +        ingredientUnits.unshift(this.recipeIngredientAttrs.ingredientMeasure);
ya buena

2021-06-13 02:36 UTC, rjherrera commented on db/schema.rb
> -  create_table "ingredient_measures", force: :cascade do |t|
jaja acabo de cachar, qué raro

2021-06-13 02:37 UTC, rjherrera commented on app/controllers/api/v1/recipes_controller.rb
> +    binding.pry
se te pasó esto, y en el último commit está sin la convención de nombres (lo de feat(), etc.)

2021-06-13 02:41 UTC, rjherrera approved these changes

2021-06-13 03:03 UTC, cacosandon requested changes
👏  se ve perfect

dejé algo que hay que cambiar 😢

2021-06-13 03:03 UTC, cacosandon commented on app/javascript/components/recipes/base/selected-ingredient-card.vue
>        this.recipeIngredientAttrs.ingredient.price / this.recipeIngredientAttrs.ingredient.quantity;
esto hay q cambiarlo!

si por ejemplo yo tengo que un ingrediente es "queque"

2 kg = 1 unidad = $1000

al principio va a salir que si agrego 1 kg son $500 en la receta, pero si cambio a unidad sigue el $500!
porq está tomando `ingredient.quantity` que es el primero. El precio siempre es el mismo pero debería tomar el quantity de la measure seleccionada

2021-06-14 16:45 UTC, cacosandon approved these changes

2021-06-14 23:43 UTC, merged