Add lider scraper
platanus/2021-1-Grupo4-Web pull request #12
Opened 2021-04-22 18:44 UTC by lldavico

### Nuevo

* Se configuraron clientes mediante la gema `pincers` para scraper de productos en Jumbo y Lider. Se obtienen los productos mediante el buscador de aquellos sitios web que aparecen en la primera vista
* Se configuró la opcion `headless` del driver de Google Chrome para evitar levantar el navegador al scrapear

Archivos a revisar:

- [ ] Ver módulos creados en `app/clients`

### QA

Ingresar a la consola de rails:

```bash

# Instalar dependencias
bundle install
yarn install

# Consola de Rails
rails c
```

```ruby
# Buscar y descargar datos de Jumbo
JumboClient.new.products_by_query(query: <producto>)

# Similar en Lider
LiderClient.new.products_by_query(query: <producto>)

```

Luego, se despliegan los datos en la consola.

### Pendiente

* Falta manejar paginación en sitios web i.e. obtener todos los productos que se obtienen en los resultados de la búsqueda, buscando por páginas
* Scrapers 'genéricos' para ahorrar código, posible refactor
* Almacenar datos de scrapers en base de datos

2021-04-22 18:45 UTC, monkeyci commented on app/clients/chrome_client.rb
> +    @browser ||= Pincers.for_webdriver(:chrome, wait_timeout: CHROME_CLIENT_TIMEOUT, options: @@options)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [104/100]

2021-04-22 18:45 UTC, monkeyci commented on app/clients/jumbo_client.rb
> +end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingEmptyLines: Final newline missing.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +    BASE_URL = 'https://www.lider.cl/supermercado/search?Ntt='
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +    def products_by_query(query: nil)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +            brand: get_brand(product),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/FirstHashElementIndentation: Use 2 spaces for indentation in a hash, relative to the first position after the preceding left parenthesis.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +          })
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/FirstHashElementIndentation: Indent the right brace the same as the first position after the preceding left parenthesis.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +          puts scraped_products.last
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-22 18:45 UTC, monkeyci commented on app/clients/lider_client.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-22 19:30 UTC, smargozzini reviewed
Se ve bien! dejo unos comentarios chicos.

Ademas arreglaría los errores de rubocop.

2021-04-22 19:30 UTC, smargozzini commented on app/clients/chrome_client.rb
> +    end
esto queda más legible con `set_headless_chrome if ENABLE_HEADLESS_CHROME`

2021-04-22 19:30 UTC, smargozzini commented on app/clients/lider_client.rb
> +      browser.goto(BASE_URL + query)
en estos casos es mejor usar interpolación de strings
`"#{BASE_URL}#{query}"`

De todas formas, creo que el `BASE_URL` está mal definido, debería ser `https://www.lider.cl/supermercado/search` y al ir a cierta página hacer `"#{BASE_URL}?Ntt=#{query}"`

2021-04-22 19:30 UTC, smargozzini commented on app/clients/lider_client.rb
> +      product.search('.product-name').text
porque se hace este `puts`

2021-04-22 19:31 UTC, smargozzini commented on app/clients/lider_client.rb
> +      product.search('.product-name').text
Me equivoque de linea, pero hay un puts un poco más arriba.

2021-04-22 23:31 UTC, cacosandon requested changes
buena lucho, resuelve lo que te alegó el mono que no se puede leer mucho

hagamos tests de esto :eye:

2021-04-24 17:12 UTC, monkeyci commented on app/clients/lider_client.rb
> +        puts scraped_products.last
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-04-24 17:36 UTC, fncabrera requested changes
Deje unos mini comentarios, QA good -> no olviden agregar a heroku el buildpack para el chrome-driver

Aproveche de arreglar y pushear los warnings de rubocop 👌

2021-04-24 17:36 UTC, fncabrera commented on app/clients/lider_client.rb
> +        puts scraped_products.last
Quitar este puts. Era para probar? ahí quizás recomiendo un binding.pry y te permite probar si está todo bien por consola

2021-04-24 17:36 UTC, fncabrera commented on app/clients/lider_client.rb
> +  BASE_URL = 'https://www.lider.cl/supermercado/search?Ntt='
Para más adelante quizás sea bueno dejar esto como una variable de entorno o manejable desde Admin para ante cualquier cambio de la URL que no sea necesario tener que entrar a editar código, que opinan?

2021-04-24 17:36 UTC, fncabrera commented on app/clients/lider_client.rb
> +      browser.search('.product-details').wait(:present, timeout: 5.0).map do |product|
no olvidar controlar el error del timeout cuando hagan la API que controla el cliente despues 👁️

2021-04-26 13:29 UTC, lldavico commented on app/clients/lider_client.rb
> +  BASE_URL = 'https://www.lider.cl/supermercado/search?Ntt='
Probablemente en algún momento tengamos que ingresar mas urls, por lo que podriamos almacenarlas en un módulo aparte quizas, mas que una variable de entorno

2021-04-26 13:30 UTC, lldavico commented on app/clients/lider_client.rb
> +  BASE_URL = 'https://www.lider.cl/supermercado/search?Ntt='
Además esas URLs son públicas, por lo que no veo algún problema en que estén en un módulo y no como variable de entorno

2021-04-26 13:43 UTC, lldavico commented on app/clients/lider_client.rb
> +      browser.goto(BASE_URL + query)
Ok!

2021-04-26 15:44 UTC, monkeyci commented on app/clients/chrome_client.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.

2021-04-26 15:44 UTC, monkeyci commented on spec/clients/lider_client_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

2021-04-26 15:44 UTC, monkeyci commented on spec/clients/lider_client_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingEmptyLines: 2 trailing blank lines detected.

2021-04-28 14:24 UTC, cacosandon commented on app/clients/jumbo_client.rb
> +end
falta un rebase! esto está en mi rama

2021-04-28 14:35 UTC, cacosandon requested changes

2021-04-28 14:35 UTC, cacosandon commented on spec/clients/lider_client_spec.rb
> +end
qué pasa si no hay offer price? faltaría un test de esto o no?

2021-04-28 14:35 UTC, cacosandon commented on spec/clients/jumbo_client_spec.rb
> +
este test tb es de mi rama!

2021-04-28 14:35 UTC, cacosandon commented on spec/clients/chrome_client_spec.rb
> +end
tb de mi rama :eye:

2021-04-28 14:35 UTC, cacosandon commented on app/clients/lider_client.rb
> +  end
en product-name viene la brand y en product-description viene el name? :thinking:

2021-04-28 14:35 UTC, cacosandon commented on app/clients/chrome_client.rb
> +end
no modificaría esto, lo hice en otra rama cuando agregué el buildpack!

2021-04-28 14:35 UTC, cacosandon commented on Gemfile.lock
>      power_api (0.2.0)
todos estos cambios de gemfile y gemfile.lock tpc son de esta rama

2021-04-28 14:35 UTC, cacosandon commented on .rspec
> +--format progress
esto tampoco es de la rama :grimacing:

2021-04-28 20:12 UTC, smargozzini approved these changes

2021-04-28 22:40 UTC, cacosandon approved these changes
recuerda hacer merge solo cuando la otra esté mergeada

2021-05-01 21:32 UTC, fncabrera approved these changes
No olvidar lo que mencionó caco y arreglar el conflicto que hay en uno de los archivos

2021-05-02 00:22 UTC, monkeyci commented on spec/clients/lider_client_spec.rb
> +RSpec.describe LiderClient do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [11/5]

2021-05-02 00:22 UTC, monkeyci commented on spec/clients/lider_client_spec.rb
> +    allow_any_instance_of(described_class).to receive(:browser).and_return(browser)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/AnyInstance: Avoid stubbing using allow_any_instance_of.

2021-05-02 00:22 UTC, monkeyci commented on spec/clients/lider_client_spec.rb
> +  describe 'getting all products with normal and offer price' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [16/5]

2021-05-02 00:48 UTC, merged