feat(front-alert): add minimum quantity to form and alert button on t…
platanus/2021-1-Grupo4-Web pull request #139
Opened 2021-06-29 01:49 UTC by miortiz1

# Que se hizo
En la topbar si es que hay algun ingrediente que este bajo el limite inferior aprece una campana en la topbar donde se listan los ingredientes que debiesen aumentar su inventario

2021-06-29 14:29 UTC, smargozzini reviewed
un comentario.
ví que se usa así en otros lados tmbn, los arreglaría todos.

2021-06-29 14:29 UTC, smargozzini commented on app/javascript/components/ingredients/ingredients-form.vue
>          ingredient_measures_attributes, /* eslint-disable-line camelcase */
pq se tiene esta variable sin camelcase? 
no es necesario saltarse esa regla, se puede definir como `ingredientMeasuresAttributes` y al hacer un request puedes usar 

```
import { decamelizeKeys } from 'humps'
...
  return axios.post('/api/v1/example', decamelizeKeys({
    ...
    },
  }))
...
```

2021-06-29 22:42 UTC, ValentinaAlvarezG requested changes
Dejé hartos comentarios, algunos quizás los podemos discutir en el grupo de web

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar.vue
> +  async created() {
Aquí no sé que tan buena práctica será, pero en volá es mejor usar un watch o algo así? (o quizás otra solución) pq me pasa que tengo que recargar la página para que se actualice lo de la campana, no se actualiza al momento que yo actualizo el inventario, ya sea que me quedo corta y necesito que aparezca la campana o que ya tengo inventario y no debería estar esa alerta. No sé @fncabrera cual es el comportamiento esperado de esto en verdad, quizás da lo mismo que se tenga que recargar la página.

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar.vue
> +        <base-spinner />
le setearía un tamaño más razonable al spinner, creo que en otros lados lo tenemos como w-8 h-8 pq está demasiado gigante.

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +      alertIngredients: 'Ingredientes acabandose',
Debería ser "acabándose"

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +      minimumQuantity: 'Cantidad minima en inventario',
"mínima"

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +      minimumQuantityShort: 'Cantidad minima',
"mínima"

2021-06-29 22:42 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar.vue
> +          {{ ingredient.inventory }}/{{ ingredient.minimumQuantity }} {{ ingredient.measure }}
Quizás esto es de mañosa no más, pero me pasó que cuando lo vi a la primera no entendí bien pq decía por ej 2/3 UN, literal mi primer pensamiento fue ¿pq dice dos tercios de unidad?. Entonces no sé, quizás encontraría una mejor manera expresar que es 2 de 3 unidades o en una tabla poner |Nombre | En inventario | Mínimo|, no sé ...es discutible.

2021-06-30 01:37 UTC, miortiz1 commented on app/javascript/components/layout/top-navbar.vue
> +  async created() {
Si abres la campana se irá, lo que pasa es que tengo que consultar en base de datos si cambio el ingrediente porque no tendre todos los ingredientes en el front, y las alertas la idea es que se vean desde cualquier parte, si haces un cambio y debieses quedar sin alertas si apretas la campana te dira que no queda nada y desaparecerá.

2021-06-30 02:25 UTC, miortiz1 commented on app/javascript/components/ingredients/ingredients-form.vue
>          ingredient_measures_attributes, /* eslint-disable-line camelcase */
arreglado

2021-06-30 02:43 UTC, miortiz1 commented on app/javascript/components/layout/top-navbar.vue
> +        <base-spinner />
Arreglado

2021-06-30 02:44 UTC, miortiz1 commented on app/javascript/components/layout/top-navbar.vue
> +          {{ ingredient.inventory }}/{{ ingredient.minimumQuantity }} {{ ingredient.measure }}
Puse en rojo el primer número, creo que ahi se entiende más, que no quería como saturar la tabla, pero mejor conversar si lo cambiamos

2021-06-30 16:01 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar.vue
> +  async created() {
oka

2021-06-30 16:04 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar.vue
> +          {{ ingredient.inventory }}/{{ ingredient.minimumQuantity }} {{ ingredient.measure }}
buena!

2021-06-30 16:04 UTC, ValentinaAlvarezG approved these changes

2021-06-30 16:06 UTC, smargozzini approved these changes

2021-07-01 02:21 UTC, merged