style(home/navbar/user): style changes in home, navbars and user login
platanus/2021-1-Grupo4-Web pull request #140
Opened 2021-06-29 19:34 UTC by fncabrera

* No se asusten que varias de las _files changed_ son archivos .svg de los iconos

**Contexto:**
- Había un home pero muy feo con un puro texto, habían iconos nada que ver en la side-bar y faltaba estilo en las nav bars y vistas de login/register.

**Lo realizado:**
- Se diseño un home que cambia si se está iniciado sesión o no.
- Se cambiaron los iconos de la side-bar (relacionados a ingredientes, menus, recetas y proveedores). También se cambió el icono de lista de compras (vista index menus) a un carrito de compras.
- Se arreglaron estilos de las vistas _/users/sign_up_ y _/users/sign_in_
- Todo lo agregado o editado se hizo responsive.
- Quite harto css innecesario en algunas vistas.

**QA:**
- Que funcionen todos los botones/links del home ('/'), iniciado sesión o no.
- Que siga funcionando bien hacer login o registrarse (y que funcione el nuevo link de abajo que permite irse a crear una cuenta o iniciar sesión respectivamente)
- Que en la side-bar ahora salga un triangulo extra según la vista en la que uno se encuentre.

Así debería verse todo:

**Home ('/)**
![image](https://user-images.githubusercontent.com/30879712/123856498-29807580-d8ef-11eb-85a9-6d6fbe66b07e.png)
![image](https://user-images.githubusercontent.com/30879712/123856554-3bfaaf00-d8ef-11eb-8bcb-381492b5814c.png)
![image](https://user-images.githubusercontent.com/30879712/123856591-49179e00-d8ef-11eb-92c2-2ffb2bd06a4e.png)

**Iniciar sesión ('users/sign_in')**
![image](https://user-images.githubusercontent.com/30879712/123856691-62204f00-d8ef-11eb-8c5a-c53be36b8177.png)

**Registrarse ('users/sign_up')**
![image](https://user-images.githubusercontent.com/30879712/123856724-6c424d80-d8ef-11eb-9c42-17c3e51a175a.png)

**Side-bar**
![image](https://user-images.githubusercontent.com/30879712/123856772-7d8b5a00-d8ef-11eb-9828-49d6fe6ab16c.png)

2021-06-29 22:21 UTC, ValentinaAlvarezG requested changes
Solo te dejé un pequeño comentario de un import, lo demás se ve todo bacán!! :raised_hands:, QA funciona todo bien.

2021-06-29 22:21 UTC, ValentinaAlvarezG commented on app/javascript/packs/application.js
> +import NavegationItem from '../components/home/navegation-item.vue';
El navigation item se usa solo en la componente landing page cierto? si es así, lo importaría solo en ese archivo pq aquí en verdad estamos dejando solo lo que se podría importar desde varias componentes  como las componentes base o las que se van a llamar directamente de una view.

2021-06-30 01:05 UTC, Arodriguez14 approved these changes
Muy bueno!

2021-06-30 20:51 UTC, ValentinaAlvarezG approved these changes

2021-06-30 21:01 UTC, merged