fix(minimum-inventory): display 0 on border cases
platanus/2021-1-Grupo4-Web pull request #150
Opened 2021-07-01 19:37 UTC by aescobar4

# Contexto
Cuando un ingrediente tiene una cantidad mínima de ingredientes, se mostraba un guión `-` o nada, lo que no era representativo, sino que poner un `0` deja claro la cantidad mínima de ingredientes. También, se aceptaban cantidades mínimas menores que 0.

# QA
Entrar a `/ingredients`, editar o crear un ingrediente y ponerle cualquier numero o dejarlo vacío. Si el número es menor que 0, debe aparecer una alerta y no dejar que se guarde es valor. Si es cualquier otro número, debe guardarse. Si no se ingresa nada, debe guardarse por defecto el valor 0.

2021-07-02 13:41 UTC, smargozzini approved these changes

2021-07-05 03:08 UTC, miortiz1 requested changes
No cache bien por que, pero probe en heroku y no me deja guardar cantidad minima ahora al editar. Tal vez estaba de antes y no cachamos pero podrías arreglarlo?

2021-07-05 16:05 UTC, fncabrera requested changes
Sobre lo que comentó miguel, efectivamente si creas un ingrediente, luego no se logra editar la cant minima de inventario

2021-07-07 20:10 UTC, aescobar4 commented
Prueben ahora, ya esta con rebase!

2021-07-07 21:07 UTC, miortiz1 approved these changes

2021-07-08 02:06 UTC, fncabrera approved these changes
esta perfe 🚀

2021-07-08 02:23 UTC, merged