Pendientes web
platanus/2021-1-Grupo4-Web pull request #168
Opened 2021-07-07 16:45 UTC by sofiadelano

## Contexto
Hay detalles de diseño que faltaban arreglar como por ejemplo que los buscadores tengan el mismo formato, que hayan las mismas distancias entre compoentnes, entre otros. Y habñian otros detalles

## Lo que hice
- Agregar mensaje de que no hay ingredientes aún cuando se quiere crear o editar una receta y todavía no se tienen ingredientes
- Agregar mensaje de que no hay recetas aún cuando se quiere crear o editar un menu y todavía no se tienen recetas creadas
- Si no se tienen los datos de transferencia de un proovedor, entonces en el popup esto se notifica y el botón para copiar los datos no aparece
- Si existen los datos de transferencia d eun proovedor estos se muestran y aparece el botón para copiar los datos al clipboard
- Poner el mismo estilo en los proovedores que en el resto de las vistas (ingredientes, recetas y menus). Es decir, agregar un buscador y que el botón de agregar proovedor esté a la derecha del boton

## QA
- Navegar por las vistas y ver que los titulos, buscadores y botones sigan el mismo formato de estilo
- Ir a proovedores, crear un proveedor con algun dato de transferencia incompleto y lueg apretar ver datos, y luego crear uno o editar ese mismo y completar todos los datos de transferencia y luego verificar que esta bien en "ver datos"
- Probar buscador de proovedores

2021-07-07 17:04 UTC, Arodriguez14 approved these changes
Esta bacán Sofi. Muy buenos detalles arreglaste.
Lo único que cambiaría es poner Cerrar en vez de Cancelar en el Pop Up de Datos Bancarios

2021-07-07 20:03 UTC, sofiadelano commented
> Esta bacán Sofi. Muy buenos detalles arreglaste.
> Lo único que cambiaría es poner Cerrar en vez de Cancelar en el Pop Up de Datos Bancarios

Eso ya está en master!! Fue cambiado en otra Pr que se acaba de mergear

2021-07-07 21:29 UTC, fncabrera requested changes
Está bacan sofi! Dos detalles
- Cuando faltan datos de cuenta bancaria el provider, el texto "Faltan los siguientes datos" quizás lo pondría en negrita y un espacio dps para que se vea más bonito
![image](https://user-images.githubusercontent.com/30879712/124831045-b8713b80-df48-11eb-860b-1cadf3466d79.png)
- Cuando no hay recetas, al crear un menu sale el msje de que aun no hay recetas para agregar, pero al editar un menu este no sale (son componentes distintas), lo agregaría ahí tb

2021-07-08 01:58 UTC, cacosandon requested changes
algunos cambios enanos, todo lo demás lo veo cool!

2021-07-08 01:58 UTC, cacosandon commented on app/javascript/locales/es.js
> +      noRecipesAvailable: 'Aún no tiene recetas para seleccionar',
```suggestion
      noRecipesAvailable: 'Aún no tienes recetas para seleccionar',
```

2021-07-08 01:58 UTC, cacosandon commented on app/javascript/components/providers/index/provider-index-component.vue
> +            class="my-2 h-10 font-bold py-2 px-6 rounded shadow-md flex-shrink-0 bg-green-500 hover:bg-green-700 text-white"
hay que meterle un cursor-pointer porq si no como que no sale pa clickears el mouse
```suggestion
            class="my-2 h-10 font-bold py-2 px-6 rounded shadow-md flex-shrink-0 bg-green-500 hover:bg-green-700 text-white cursor-pointer"
```

2021-07-08 01:58 UTC, cacosandon commented on app/javascript/locales/es.js
> +      noNameAlert: 'Ingresa el nombre del menú por favor',
```suggestion
      noNameAlert: 'Debes ingresar el nombre del menú',
```

2021-07-08 14:47 UTC, fncabrera reviewed
Que este botón diga Cerrar en vez de Cancelar, lo demás 🚀 
![image](https://user-images.githubusercontent.com/30879712/124942684-d8047480-dfd9-11eb-9297-15319fd5609a.png)

2021-07-08 15:21 UTC, cacosandon approved these changes

2021-07-08 15:24 UTC, Arodriguez14 approved these changes

2021-07-08 17:02 UTC, fncabrera approved these changes

2021-07-08 17:02 UTC, merged