feat(provider-validations): add validations for providers
platanus/2021-1-Grupo4-Web pull request #169
Opened 2021-07-07 17:30 UTC by ValentinaAlvarezG

# Lo que hice
Agregar validaciones para los proveedores, tanto para agregar como para editar

# QA

Verificar que en los siguientes casos se muestren los respectivos mensajes. Esto para el form de crear y editar proveedores:

- Si no se ingresa un nombre --> Campo obligatorio
- Si ingresa un correo y este no es válido --> Este correo no es válido
- Si ingresa tiempo de entrega y no es mayor o igual a cero --> Debe ser mayor o igual  a cero
- Si ingresa minimo de compra y no es un entero mayor o igual a cero --> Debe ser un entero mayor o igual a cero
- Si se ingresa algunos de los campos en la parte de datos bancarios --> los demás dice Campo obligatorio (incluido Correo que estaba más arriba). Si se deja en blanco ese campo (es decir están todos en blanco) --> Deja de decir Campo obligatorio en los demás.
- Si se ingresa un nombre de proveedor que ya existe --> se cierra el modal y en index aparece un recuadro rojo con el mensaje de que el proveedor ya está existe.

2021-07-07 18:07 UTC, agomezcampero requested changes
Un par de cosas
- deberías crear un componente para mostrar errores, para evitar poner el mismo p con todas las clases de tailwind tantas veces y que sea solamente <error-msg>Mensaje</error-msg>
- esta librería es muy buena para validaciones: https://vee-validate.logaretm.com/v4/, no esta mal lo que hiciste, pero sería más limpio con esta librería
- similar a lo de los errores, creo que debería existir un componente base para alertas que pueda tener estado success o error (y así setear el color)

2021-07-07 18:07 UTC, agomezcampero commented on app/javascript/components/providers/index/provider-index-component.vue
> +        console.log()
se te quedó un console.log

2021-07-07 20:29 UTC, miortiz1 approved these changes
Esta bacan! no le encuentro ada raro al codigo, aparte de lo que ya te comentaron, que tal vez es mejor hacer una componente especial para esas alertas!
Y en la app me funcionó todo y no logré echarme nada

2021-07-12 17:11 UTC, agomezcampero approved these changes
Mucho mejor 😄

2021-07-13 04:02 UTC, miortiz1 approved these changes
coolisimo

2021-07-13 13:21 UTC, merged