New ingredient back arrow
platanus/2021-1-Grupo4-Web pull request #170
Opened 2021-07-07 22:46 UTC by aescobar4

Agregué una flecha al modal de crear ingrediente de manera que, cuando se quiera volver a buscar un ingrediente en supermercado, sea más fácil y menos tedioso.

# QA
- Ir a ingredientes, buscar uno por scrapper y apretar agregar. En el modal de editar ingrediente debe aparecer una flecha para volver. Si se apreta se puede volver a buscar un ingrediente.

2021-07-07 22:48 UTC, jgmontoya approved these changes
Buena!

2021-07-08 00:36 UTC, fncabrera requested changes
Buena Agustin! Eso si, sería bacán si logras conservar el resultado de la busqueda anterior (avísame si te complica) y cambiaría la flecha por una de color blanco (si no, no se nota mucho por el color negro del header del modal)

2021-07-08 00:53 UTC, Arodriguez14 approved these changes
Buenisimo Agustin! Esta bacán! Pero trataría de cambiar el color de la flecha para que se note mas!

2021-07-10 00:57 UTC, aescobar4 commented
Ahora la flecha redirige a la busqueda antigua del scrapper. En caso que se agregue un ingrediente desde 0, la flecha debe redirigir al index de ingredientes.

# Nuevo QA
Naveguen por todo crear ingredientes. Deberia funcionar en todos los casos, en particular probe apretando cancelar y aceptar en todos los modal para crear, apretando afuera del modal y apretando la flecha para atras. La forma de saber si no funciona es que haciendo alguna accion y despues quieran crear un nuevo ingrediente por scrapper, no se les abra el modal de scrapper. Le doy importancia porque la forma de arreglarlo fue cambiando un estilo que depende de la variable `invisible`, si esta variable no se actualiza correctamente, el modal no funciona y baja la calidad de la pagina.

2021-07-12 17:34 UTC, fncabrera approved these changes
Veo todo bien, crack

2021-07-12 17:37 UTC, merged