Refactor login
platanus/2021-1-Grupo4-Web pull request #171
Opened 2021-07-08 00:01 UTC by sofiadelano

## Lo que hice
Refactor de estilo de:
- Login: users/signin
- Signup: users/signup
- Landing Page: /

#QA
Navegar entre signup, login y landing page y probar diferentes cosas, crear usuarios, etc, y probar que no se haya perdido la funcionalidad.

2021-07-08 01:25 UTC, aescobar4 approved these changes
Like!

2021-07-08 01:53 UTC, fncabrera requested changes
Está bacán sofi, pero le haría unos cambios en estilo
![image](https://user-images.githubusercontent.com/30879712/124849466-d486d400-df6c-11eb-8dcc-536682b82708.png)
- En el home, al subtitulo y comienza ya, les podría el mismo color que el titulo (segun figma esto, pa mantener el estilo)
- El subtitulo ("la nueva forma...") debería ser "text-xl" en clase, así como el titulo es 3xl (eso esta good) -> ojo con cambiarlo en las 3 vistas
- (esto más opinion mía), siento que los botones se ven muy chicos pa lo ancho de la pagina, les mantendría el ancho anterior que tenían
![image](https://user-images.githubusercontent.com/30879712/124849634-216aaa80-df6d-11eb-8ecc-071633a89ee5.png)
- subtitulo ("la nueva forma...") del color del titulo ("bienvenido...")
- Boton de iniciar sesión que diga "Ingresar" (segun figma)

Yyyyy, esta raro el largo del cuadro de registrarse o iniciar sesión, en el caso de iniciar sesión se ve pegado al fondo de la pantalla (debería terminar antes creo), y para registrarse se ve raro -> 
![image](https://user-images.githubusercontent.com/30879712/124849956-c4232900-df6d-11eb-88b1-e2b187befaa6.png)

2021-07-08 02:03 UTC, aescobar4 commented
Curioso el ultimo comentario, a mi no me aparece asi en el deploy de heroku

2021-07-08 18:27 UTC, fncabrera requested changes
Holi, está bacán 🚀 Unos detalles:
- viendo el diseño en figma, noté que el sign in y sign up debería ser más anchos
- Cuando se inicia sesión y se ven los cuatro bloques, no sientes que quizás están dms juntos?
- Te comente abajo de unas partes de css que _creo_ que no son necesarias

Pd metí un commit del diseño de la landing page sin iniciar sesión (que creo que se ven mejor así los botones, pero pasame máquina si crees que no)

2021-07-08 18:27 UTC, fncabrera commented on app/javascript/components/landing-page.vue
> +  <div class="mt-10 flex flex-col items-center">
Creo que no es necesario ese items-center pq solo alinea centralmente en el eje Y

2021-07-08 18:27 UTC, fncabrera commented on app/javascript/components/landing-page.vue
> +    <div class="flex flex-col justify-center items-center p-12 rounded flex-none flex-grow-0 w-auto">
Creo que el items-center y rounded no hacen diferencia si están o no (probaría igual)

2021-07-09 20:35 UTC, difernandez approved these changes

2021-07-11 16:30 UTC, fncabrera approved these changes

2021-07-11 16:31 UTC, merged