Fix web details
platanus/2021-1-Grupo4-Web pull request #173
Opened 2021-07-08 01:57 UTC by aescobar4

# Contexto
Se arreglaron 3 detalles:
- Cuando se edita o crea un ingrediente, el placeholder de la unidad era cantidad, se cambio por un placeholder que indica la unidad que se esta usando
- Al editar varios inventarios, no se puede ingresar numeros negativos, ya sea escribiendolos o apretando las flechas.
- Crear y editar recetas tienen un nuevo estilo en la parte de los pasos 

# QA
Crear o editar un ingrediente y fijarse en el placeholder de las unidades. Entrar a editar varios inventarios y tratar de poner numeros negativos. Editar o crear una receta y ver el estilo nuevo. Todo deberia funcionar correctamente.

2021-07-08 13:53 UTC, sofiadelano requested changes
Si me dejó poner numeros negativos en el cambio de inventario 
![Captura de Pantalla 2021-07-08 a la(s) 09 51 53](https://user-images.githubusercontent.com/48369511/124933926-46453900-dfd2-11eb-8b6d-6f89d618fda5.png)

2021-07-08 21:21 UTC, ankaph reviewed
Dejé unos comentarios de typos, y una posible solución que podrían probar para el mínimo del input

2021-07-08 21:21 UTC, ankaph commented on app/javascript/components/recipes/base/recipe-steps.vue
> +        class="w-full h-24 bg-white border border-gray-300 box-boder rounded flex-none flex-grow-1 px-3 py-0.5"
hay un typo: `box-boder` en vez de `box-border`

2021-07-08 21:21 UTC, ankaph commented on app/javascript/components/recipes/base/recipe-steps.vue
> +    rounded-md flex-none flex-grow-0 font-ans font-normal text-base text-white w-48 bg-yellow-500
creo que `font-ans` debiese ser `font-sans`

2021-07-08 21:21 UTC, ankaph commented on app/javascript/components/ingredients/inventory-table.vue
> +                oninput="validity.valid||(value='');"
no cacho bien por qué no funciona lo de limitar a números positivos, pero me tinca que en vez de `(value='')` debiese ser `(increaseInventoryIn[idx] = 0)`. No garantizo nada jajaj

2021-07-09 14:37 UTC, aescobar4 commented on app/javascript/components/ingredients/inventory-table.vue
> +                oninput="validity.valid||(value='');"
Ya lo arregle, lo que pasa es que solo lo puse en 1 input, no los dos

2021-07-09 14:49 UTC, aescobar4 commented
Arregle el problema que mostro la Sofia, ademas los errores de Alvaro. Tambien le arregle un manejo de error cuando el no se pone nada en el input, en ese caso antes tiraba NaN y no se guardaban los cambios, ahora si se deja vacio, se toma como 0 no mas

2021-07-09 14:50 UTC, ankaph approved these changes

2021-07-10 14:03 UTC, sofiadelano approved these changes
Bacan!

2021-07-10 14:04 UTC, merged