fix(twoScrollbars): Now there is only one scrollbar everywhere
platanus/2021-1-Grupo4-Web pull request #175
Opened 2021-07-10 15:02 UTC by aescobar4

# Contexto
Antes habian 2 scrollbar como se ve en la foto, pero es innecesario. Ahora hay solo una. El codigo cambio en 1 linea no mas, asi que es mas importante el QA.

# QA
Revisar todas las vistas y ver que no hayan 2 scrollbar ni que haya perdida de informacion. Hay que rellenar con datos hasta que aparezca la scrollbar y ahi ver si esta funcionando bien.

![Screenshot from 2021-07-10 10-55-15](https://user-images.githubusercontent.com/48262100/125167198-58a7aa00-e16d-11eb-883d-592b0dbff16a.png)

2021-07-10 23:20 UTC, fncabrera requested changes
No estoy seguro de si esto es lo correcto pq se está escondiendo el srollbar como por defecto de la página y dejando los de cada componente (esperaría a que Platanus corriga, o @cacosandon que opinai?)

Y el hecho que se haga así, me pasa que nunca se ve el final del scroll:
![image](https://user-images.githubusercontent.com/30879712/125178512-bd85f300-e1b3-11eb-89fe-5e1626c4ac12.png)

Si es que es válido, demosle no más, pero creo que lo correcto sería quitar el scroll de cada componente (porque debería bastar con el por defecto), el problema que tuve yo tratando de solucionar eso la otra vez, es que la sidebar quedaba cortada (no mantenía el color hasta el final cuando había scroll)

2021-07-11 02:39 UTC, aescobar4 commented
Entiendo tu punto, pero lo hice así por dos razones, la primera era que me iba a pasar el mismo problema que dijiste, que la barra lateral se corta, pero la segunda fue por un tema de usabilidad, es más fácil y cómodo tener la side navbar y la top navbar siempre disponibles, por ejemplo, si estoy al final de la lista de ingredientes y quiero irme a recetas, tendría que subir toda la página para eso. No sé si se podrá (yo creo que sí), pero quizás se puede fijar las 2 navbar y hacer la página entera scrolleable. Eso arregla todos los problemas, así que voy a averiguar mañana, avísenme cualquier cosa

2021-07-12 17:32 UTC, fncabrera requested changes
Se ve bien el scroll bar ahora, pero parece que al haber usado fixed en la navbar lateral, hace que el padding de las componentes como tablas empiecen a contar desde el principio de la navbar o no cuando termina, y pasa esto -> (no hay padding/margen izquierdo, a diferencia de la derecha)

![image](https://user-images.githubusercontent.com/30879712/125331034-76b00e80-e315-11eb-9d05-4963adac9cfd.png)

2021-07-15 02:47 UTC, fncabrera approved these changes
Buena Agustin! Aproveche de meter un commit de lo que te había comentado (ese class mal escrito), y tb aproveche de sacar el container de las vistas, entonces ahora si uno se aleja, la tabla/componentes no se achican sino que mantiene el tamaño.

También hice un rebase para solucionar los conflictos 👌

2021-07-15 03:42 UTC, merged