refactor(validations): add refactor to validations for ingredients, recipes and menus
platanus/2021-1-Grupo4-Web pull request #188
Opened 2021-07-12 13:33 UTC by ValentinaAlvarezG

BASE #169 

# Lo que hice

Refactor de validaciones para ingredientes, recetas y menú, usando componentes para alertas, párrafos de error y usando las funciones de validación que se encuentran en `utils`.

# QA

Dar una repasada a lo siguiente y corroborar que esté siga funcionando (probar con diferentes inputs: negativos, cero, decimales, enteros, dejar en blanco, mails no válidos, letras en algún input que debería ser número, agregar algo con un nombre de algo que ya existe y **ver que los errores mostrados tienen sentido**. No debería aparecer ninguna alerta del navegador):

- Form de agregar ingrediente
- Form de editar ingrediente
- Form de editar ingrediente cuando se busca en supermercado
- Crear receta
- Editar receta
- Crear menú
- Editar menú

2021-07-12 16:02 UTC, aescobar4 requested changes
No me deja agregar ingredientes manual o por scrapper y los filtros de recetas no tienen validaciones! (Pongo fotos de lo que me sale) Tambien, el input del scrapper no tiene validacion, asi que se puede buscar como input vacio. No tira nada, pero se podria arreglar. 

Aparte, los menus y recetas se pueden crear sin recetas, ingredientes o pasos (cada cual con lo suyo), pero eso no se si entra en esta PR. 

El resto de las validaciones se ve bien.

![Screenshot from 2021-07-12 11-52-20](https://user-images.githubusercontent.com/48262100/125319332-aa386c00-e308-11eb-9491-056c3df48c71.png)
![Screenshot from 2021-07-12 11-55-21](https://user-images.githubusercontent.com/48262100/125319336-ab699900-e308-11eb-8a8c-749e0648e5a3.png)

2021-07-12 16:09 UTC, aescobar4 commented on app/javascript/components/ingredients/ingredients-container.vue
>        const validForm = !(Object.values(this.errors).some(value => !!value));
```suggestion
      return !(Object.values(this.errors).some(value => !!value));
```
Se podria hacer eso y borrar el `return validForm`, lo q ademas hace que el `// eslint-disable-next-line max-statements` de arriba ya no sea necesario

2021-07-12 16:27 UTC, aescobar4 commented on app/javascript/components/recipes/edit/recipe-edit.vue
>        this.status = status;
Estas lineas habria que borrarlas, porque se borro el `status` en `data()`

2021-07-12 17:50 UTC, ValentinaAlvarezG commented
> No me deja agregar ingredientes manual o por scrapper y los filtros de recetas no tienen validaciones! (Pongo fotos de lo que me sale) Tambien, el input del scrapper no tiene validacion, asi que se puede buscar como input vacio. No tira nada, pero se podria arreglar.
> 
> Aparte, los menus y recetas se pueden crear sin recetas, ingredientes o pasos (cada cual con lo suyo), pero eso no se si entra en esta PR.
> 
> El resto de las validaciones se ve bien.
> 
> ![Screenshot from 2021-07-12 11-52-20](https://user-images.githubusercontent.com/48262100/125319332-aa386c00-e308-11eb-9491-056c3df48c71.png)
> ![Screenshot from 2021-07-12 11-55-21](https://user-images.githubusercontent.com/48262100/125319336-ab699900-e308-11eb-8a8c-749e0648e5a3.png)

Arreglé las primeras cosas que dijiste, pero la idea es que puedas al principio crear una receta sin ingredientes, y un menú sin recetas (onda alomejor solo quieres crear de una todos solo con nombre y después te poner a agregar ingredientes y recetas), así que eso no lo toqué.

En verdad ni había considerado hacer validaciones en los filtros pq se me había olvidado que existían pero ahí los agregué para que lo pruebes. También le agregué la validación al buscador del scrapper.

2021-07-13 15:44 UTC, aescobar4 commented on app/javascript/components/ingredients/search-market-ingredients.vue
> +      unexpectedError: true,
Esta bien que esto se inicie como true? Cada vez que abro el modal del scrapper, me aparece lo de la foto!
![Screenshot from 2021-07-13 11-35-19](https://user-images.githubusercontent.com/48262100/125482966-a18c0de3-56b9-4917-b17b-61d296b28de3.png)

2021-07-13 15:47 UTC, aescobar4 requested changes
Esta todo bien, lo unico a arreglar es el comentario que te puse mas arriba y ahi la apruebo!

2021-07-13 15:50 UTC, ValentinaAlvarezG commented on app/javascript/components/ingredients/search-market-ingredients.vue
> +      unexpectedError: true,
No, no está bien jajaja sorry se me pasó cambiarlo a false, ahí lo arreglé.

2021-07-13 15:58 UTC, aescobar4 approved these changes

2021-07-13 21:28 UTC, iaacosta approved these changes

2021-07-13 22:04 UTC, merged