feat(app): change texts and add money input
platanus/2021-1-Grupo4-Web pull request #196
Opened 2021-07-14 05:23 UTC by cacosandon

Cambio algunos textos y agrego un input de $$

Video:

https://user-images.githubusercontent.com/30879716/125567201-a432058c-d7bf-4f67-93cb-24e9e98d9c29.mov

### QA

`yarn install`
Entrar a crear/editar/scraper ingredientes y modificar el precio en el input.

2021-07-14 15:51 UTC, rjherrera requested changes
se ve bien! pero incluiste el package-lock.json que no debería ir jaja

2021-07-14 22:32 UTC, fncabrera reviewed
Buena Caco, está bacán! Quizás aprovecharia esta PR para agregar otras cosas cosas (o si queri para dps no más):
- Dejar el input del proveedor como disabled -> sombreado (siento que como se ve ahora, no es intuitivo que no se pueda cambiar, y es raro que no se pueda hacer nada)
- Ahora lo del scrapper viene con unidades, pero no se generan automaticamente las transformaciones, por ej, si viene algo con Gramo, no se genera el Kilo por defecto

2021-07-14 23:05 UTC, cacosandon commented
> se ve bien! pero incluiste el package-lock.json que no debería ir jaja

fallé jaja, lo subí con .gitignore, te pido el review dps de los cambios que me pidió pipe

2021-07-14 23:13 UTC, cacosandon commented
> Buena Caco, está bacán! Quizás aprovecharia esta PR para agregar otras cosas cosas (o si queri para dps no más):
> 
> * Dejar el input del proveedor como disabled -> sombreado (siento que como se ve ahora, no es intuitivo que no se pueda cambiar, y es raro que no se pueda hacer nada)
> * Ahora lo del scrapper viene con unidades, pero no se generan automaticamente las transformaciones, por ej, si viene algo con Gramo, no se genera el Kilo por defecto

ready joven

2021-07-14 23:22 UTC, rjherrera commented on .gitignore
> +package-lock.json
un detalle, si bien no está mal agregarlo al ignore, el problema "subyacente" es que no se debería nunca mezclar npm con yarn, entonces ignorarlo como que esconde el problema. Trataría de asegurarme de que todos usen el mismo, ya sea npm o yarn, y que se incluya el lock solo del que corresponda

2021-07-14 23:22 UTC, rjherrera approved these changes

2021-07-15 02:57 UTC, fncabrera approved these changes
🚀

2021-07-15 02:57 UTC, merged