Detalles pendientes web
platanus/2021-1-Grupo4-Web pull request #202
Opened 2021-07-15 18:56 UTC by sofiadelano

2021-07-15 19:11 UTC, monkeyci commented on app/javascript/components/recipes/edit/recipe-edit.vue
> +              type="number"
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parsing error: duplicate-attribute  vue/no-parsing-error

2021-07-15 19:11 UTC, monkeyci commented on app/javascript/components/recipes/edit/recipe-edit.vue
> +              type="number"
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Duplicate attribute 'type'          vue/no-duplicate-attributes

2021-07-15 19:11 UTC, monkeyci commented on app/javascript/components/recipes/edit/recipe-edit.vue
> +              type="number"
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parsing error: duplicate-attribute  vue/no-parsing-error

2021-07-15 19:11 UTC, monkeyci commented on app/javascript/components/recipes/edit/recipe-edit.vue
> +              type="number"
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Duplicate attribute 'type'          vue/no-duplicate-attributes

2021-07-15 19:21 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-list/recipes-item.vue
> +    <div class="flex flex-row w-10/12 justify-between items-center p-6 static h-24 bg-white flex-none flex-grow-0 self-stretch"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'class' should be on a new line                      vue/max-attributes-per-line

2021-07-15 19:21 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-list/recipes-item.vue
> +    @click="goToRecipe"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 9 spaces but found 4 spaces  vue/html-indent

2021-07-15 19:21 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-list/recipes-item.vue
> +  >
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 4 spaces but found 2 spaces  vue/html-indent

2021-07-16 17:03 UTC, fncabrera requested changes
Buena pega sofi 👏 Algunos detalles que pille:
- Al crear/editar ingredientes, las opciones de unidades se ve mal ahora: 
![image](https://user-images.githubusercontent.com/30879712/125982847-c6a41d39-692b-4a1d-be45-8d94a1b484bb.png)
- Cuando se crean las unidades repetidas, hay dos cruces para eliminarlas y el espacio del input de unidades queda muy chico (dejaría la cruz grande):
![image](https://user-images.githubusercontent.com/30879712/125982906-1ac9e83f-2003-4fd6-a6f0-4717a5ad1d28.png)
- En el index de recetas, ahora todo el cuadro es clickeable para irse al show, pero el mouse no se pone como con la figura de "mano" cuando algo es link -> Para hacer que un div se comporte así, creo que se hace con [esto](https://tailwindcss.com/docs/cursor)
- El boton editar proveedor queda un poco más chico verticalmente que el eliminar pq el eliminar tiene border-2, quizás agrandar un poco el de editar verticalmente para que queden iguales

2021-07-16 19:22 UTC, fncabrera approved these changes
🚀

2021-07-16 20:22 UTC, Arodriguez14 approved these changes

2021-07-16 20:23 UTC, merged