fix(minInventory): add chance to edit min inventory in index
platanus/2021-1-Grupo4-Web pull request #204
Opened 2021-07-16 20:48 UTC by Arodriguez14

### Lo que se hizo
Ahora se puede editar el mínimo inventario en el index de ingredientes.
En caso de que al crear un ingrediente no se llene el mínimo, se crea con 0.

### QA
Ir a ingredientes y cambiar el mínimo inventario en el index.
Agregar nuevos ingredientes y ver que el mínmo es 0 en caso de que el usuario no lo ponga.

2021-07-18 20:25 UTC, aescobar4 requested changes
Esta todo bien! Lo unico que no funciona es apretar el lapiz para editar, como que no hace nada

2021-07-18 22:11 UTC, Arodriguez14 commented
> Esta todo bien! Lo unico que no funciona es apretar el lapiz para editar, como que no hace nada

Esque el lapiz es para que el usuario se de cuenta que puede editarlo ahi mismo. Quizas no se entiende mucho, que opinay? Pero hacer click en el lapiz no hace nada

2021-07-18 23:58 UTC, aescobar4 commented
> Esque el lapiz es para que el usuario se de cuenta que puede editarlo ahi mismo. Quizas no se entiende mucho, que opinay? Pero hacer click en el lapiz no hace nada

Aaah perfecto, esta bien entonces, pensé que tenía la misma funcionalidad que editar inventario (no el mínimo)

2021-07-18 23:58 UTC, aescobar4 approved these changes

2021-07-19 00:23 UTC, monkeyci commented on app/javascript/components/ingredients/ingredients-table.vue
> +      console.log("minimum", idx)
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-07-19 00:23 UTC, monkeyci commented on app/javascript/components/ingredients/ingredients-table.vue
> +      console.log("minimum", idx)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Strings must use singlequote  quotes

2021-07-19 00:23 UTC, monkeyci commented on app/javascript/components/ingredients/ingredients-table.vue
> +      console.log("minimum", idx)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon             semi

2021-07-19 00:23 UTC, Arodriguez14 commented
> > Esque el lapiz es para que el usuario se de cuenta que puede editarlo ahi mismo. Quizas no se entiende mucho, que opinay? Pero hacer click en el lapiz no hace nada
> 
> Aaah perfecto, esta bien entonces, pensé que tenía la misma funcionalidad que editar inventario (no el mínimo)

Ya cache a lo que te referias Agustin! Mala mía jajajaj ya lo arregle. Gracias por el comentario!

2021-07-19 02:18 UTC, fncabrera approved these changes
🚀

2021-07-19 02:19 UTC, merged