Web validations refactor
platanus/2021-1-Grupo4-Web pull request #209
Opened 2021-07-18 21:16 UTC by ValentinaAlvarezG

Esto era de la PR #188  que estaba aprobada solo que hubo un error y se había mergeado a su base y no a master.

# Lo que hice
Refactor de validaciones para ingredientes, recetas y menú, usando componentes para alertas, párrafos de error y usando las funciones de validación que se encuentran en utils.

# QA
Dar una repasada a lo siguiente y corroborar que esté siga funcionando (probar con diferentes inputs: negativos, cero, decimales, enteros, dejar en blanco, mails no válidos, letras en algún input que debería ser número, agregar algo con un nombre de algo que ya existe y ver que los errores mostrados tienen sentido. No debería aparecer ninguna alerta del navegador):

Form de agregar ingrediente
Form de editar ingrediente
Form de editar ingrediente cuando se busca en supermercado
Crear receta
Editar receta
Crear menú
Editar menú

2021-07-18 21:45 UTC, cacosandon approved these changes

2021-07-19 02:30 UTC, fncabrera requested changes
El **edit y create** de recetas se rompió (solo la parte de datos básicos):
![image](https://user-images.githubusercontent.com/30879712/126094230-5aa8e310-e512-4e8e-8cbd-df2e27260afd.png)
Y por lo que caché, harto del css voviste a una versión anterior -> dejaría en su mayoría lo que está en master pq esos cambios fueron pa hacerlo responsive. Usando lo que está en master (el css de los divs) debería solucionarlo rapidito (si queri estar segura de si está bien en términos de responsive, podi compararlo con el comportamiento de staging)

Lo demás todo perfect!

2021-07-19 12:07 UTC, monkeyci commented on app/javascript/components/recipes/new/recipe-create.vue
> +  </div>
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parsing error: x-invalid-end-tag  vue/no-parsing-error

2021-07-19 14:42 UTC, fncabrera approved these changes
🚀

2021-07-19 14:52 UTC, merged