feat(ingredients-form): duplicated measures
platanus/2021-1-Grupo4-Web pull request #212
Opened 2021-07-18 23:01 UTC by cacosandon

BASE #209 

Algunos arreglos de diseño y validaciones:
- Ahora las validaciones de quantity y measure son de todas, no solo la primera
- Medidas duplicadas

![image](https://user-images.githubusercontent.com/30879716/126084716-c11766d7-7dea-422a-b4e1-4dd9da510333.png)

Antes si habían medidas duplicadas simplemente decía "Oops ocurrió un error"

2021-07-19 01:27 UTC, fncabrera requested changes
Buena caco! Pille este error, te dejo el flujo:
1. Creo un ingrediente y se guarda
2. Entro a editarlo, elimino una de las medidas alternativas y guardo
3. Entro a editar de nuevo, y sigue apareciendo el espacio para crear una nueva medida alternativa, si pongo Guardar sin tocarlo, me dice que es campo obligatorio. Si es que apreto cruz (para eliminar ese input de medida alternativa) y guardo, sale "Ha ocurrido un error inesperado". También pasa eso si es que trato de agregar una medida alternativa en ese input vacio.

2021-07-20 02:17 UTC, monkeyci commented on app/controllers/api/v1/ingredients_controller.rb
> +      :id, :name, :quantity, :primary, :_destroy
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/FirstArrayElementIndentation: Use 2 spaces for indentation in an array, relative to the first position after the preceding left parenthesis.

2021-07-20 02:17 UTC, monkeyci commented on app/controllers/api/v1/ingredients_controller.rb
> +    ])
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/FirstArrayElementIndentation: Indent the right bracket the same as the first position after the preceding left parenthesis.

2021-07-20 15:22 UTC, fncabrera approved these changes

2021-07-20 15:32 UTC, Arodriguez14 approved these changes

2021-07-20 15:32 UTC, merged