Recipe controller
platanus/2021-1-Grupo4-Web pull request #25
Opened 2021-04-29 01:48 UTC by Arodriguez14

### Contexto
Card: https://trello.com/c/eIpVd0z7/3-crud-de-recetas-api
CRUD de recipe listo.

### Lo que hice

Se hizo el controlador de receta mediante el comando de power api. Además de eso, se editaron los test y el controlador para poder asociar las recetas con los usuarios y ingredientes.

### QA
Para probar lo hecho hay que correr la app con rails s y luego ir a http://localhost:3000/api-docs/index.html, en donde se podrá crear recetas, editarlas, obtenerlas y eliminarlas mediante los métodos http. (Se adjunta foto). Aquí lo importante es que para un usuario se le debe mostrar las recetas que son de el y no de otros usuarios.
![Captura de pantalla 2021-04-28 a la(s) 21 13 37](https://user-images.githubusercontent.com/48296628/116492505-6934cd80-a86a-11eb-9c42-14b6f2792ae7.png)

### Pendiente
Mostrar los ingredientes de cada receta y calcular precio. Esto se implementará después de hacer merge con el controller de ingredientes.

2021-04-29 01:49 UTC, monkeyci commented on spec/integration/api/v1/recipes_spec.rb
> +describe 'API::V1::Recipes', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/EmptyExampleGroup: Empty example group detected.

2021-04-29 01:49 UTC, monkeyci commented on spec/integration/api/v1/recipes_spec.rb
> +describe 'API::V1::Recipes', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [8/5]

2021-04-29 21:26 UTC, cacosandon requested changes
Buena, se ve todo bien. En la PR de fede comentaron una mejor forma de sacar los objetos de un usuario, te recomiendo mirar esos comentarios!

2021-04-30 15:04 UTC, ankaph reviewed
Dejé un par de comentarios!

2021-05-01 14:57 UTC, Arodriguez14 commented on spec/integration/api/v1/recipes_spec.rb
> +        5.times do |_time|
Toda la razón en tus comentarios. Hice los cambios que me comentaste y un par mas que vi en otras PR! Gracias!!

2021-05-01 14:58 UTC, Arodriguez14 commented
> Buena, se ve todo bien. En la PR de fede comentaron una mejor forma de sacar los objetos de un usuario, te recomiendo mirar esos comentarios!

Gracias Caco! Revise la PR de ingredients con los cambios que le hiciste y eso me sirvió para cambiar esta. Te pasaste!

2021-05-01 23:07 UTC, fncabrera reviewed
Se ve todo bien! Ojo con unas alertas que hay del bot de rubocop y tengo algunos comentarios que en realidad son los mismos que deje en la PR de Fede
https://github.com/platanus/2021-1-Grupo4-Web/pull/26#pullrequestreview-649822849

2021-05-02 15:28 UTC, fncabrera commented
Como dato, los comentarios que dejé, ya los arregló caco en la PR #26 🚀 

Pd no olvidar resolver los conflictos en files que salen

2021-05-02 23:40 UTC, monkeyci commented on spec/swagger/v1/schemas/recipe_schema.rb
> +    cook_minutes: { type: :integer, example: 666, 'x-nullable': true },
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInHashLiteral: Avoid comma after the last item of a hash.

2021-05-02 23:53 UTC, Arodriguez14 commented
> QA bien en general, se ve todo bien! Tengo algunos comentarios que en realidad son los mismos que deje en la PR de Fede
> [#26 (review)](https://github.com/platanus/2021-1-Grupo4-Web/pull/26#pullrequestreview-649822849)

Listo con esos cambios. Además hice rebase para que esté actualizada con master. Quedo a la espera de la confirmación para hacer el Merge. 

Gracias a todos!!

2021-05-03 01:17 UTC, cacosandon approved these changes

2021-05-03 12:37 UTC, ankaph approved these changes

2021-05-03 19:09 UTC, fncabrera requested changes
Todo bien, pero ojo que el Post y Update de Recipes no tiene el example de body (se que caco lo hizo en la PR #26 que ya se hizo merge por si querí echarle un ojo)

2021-05-04 00:16 UTC, monkeyci commented on spec/integration/api/v1/recipes_spec.rb
> +describe 'API::V1::Recipes', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [9/5]

2021-05-04 21:05 UTC, fncabrera approved these changes
Buenísimo @Arodriguez14 🚀 ! Ojo con un reclamo en los tests que tiró rubocop, @cacosandon cachai como resolver ese? es bien tipico parece. Arregla esto y haz merge

2021-05-05 01:45 UTC, merged