Ingredient controller
platanus/2021-1-Grupo4-Web pull request #26
Opened 2021-04-29 02:05 UTC by fthurtado

Se creó la api de Ingredients a través de la gema power-api.
https://trello.com/c/WWGgdxJc/2-crud-de-ingredientes-api

Para revisar:
1. Controller
2. Routes
3. Serializer
4. Tests

## QA

- Correr servidor (rails s)
  - Meterse a localhost:3000/api-docs
    - Crear o Ingresar con usuario y copiar token
    - Crear / Editar / Eliminar ingredientes con datos de usuario (mail y token)
      - Al no ocupar datos de usuario válidas debería levantar error
    - Crear otro usuario y hacer requests de todos los ingredientes
      - Debería devolver una lista vacía
    - Hacer Requests con primer usuario
      - Debería entregar los ingredientes creados anteriormente
 
<img width="1417" alt="Screen Shot 2021-04-28 at 21 57 39" src="https://user-images.githubusercontent.com/48318555/116493746-5d96d600-a86d-11eb-9217-733ffe562d1d.png">

## Pendiente desde nuevas ramas

- Entregar ingredientes a recetas y ¿proveedores? específicos.

2021-04-29 02:06 UTC, monkeyci commented on spec/integration/api/v1/ingredients_spec.rb
> +describe 'API::V1::Ingredients', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/EmptyExampleGroup: Empty example group detected.

2021-04-29 02:06 UTC, monkeyci commented on spec/integration/api/v1/ingredients_spec.rb
> +describe 'API::V1::Ingredients', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [9/5]

2021-04-29 11:55 UTC, lldavico reviewed
Buena buena, faltaria arreglar el par de cops que te comentaron nomas

2021-04-29 14:26 UTC, rjherrera reviewed
está bueno! te puse un comentario por si lo quieres revisar!

2021-04-29 23:08 UTC, cacosandon commented on app/controllers/api/v1/ingredients_controller.rb
> +    respond_with Ingredient.where(user_id: current_user.id)
buenísima! yo tomo la PR ahora por cambio de roles
aplico los cambios altoque, se entiende mucho mejor

2021-04-29 23:24 UTC, cacosandon commented on spec/integration/api/v1/ingredients_spec.rb
> +describe 'API::V1::Ingredients', swagger_doc: 'v1/swagger.json' do
este lo bajé a 7, pero me tinca que está fallado por ser de swagger. En cada scope ocupo máximo 4 o 5

2021-04-29 23:24 UTC, monkeyci commented on spec/integration/api/v1/ingredients_spec.rb
> +describe 'API::V1::Ingredients', swagger_doc: 'v1/swagger.json' do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [7/5]

2021-04-29 23:37 UTC, rjherrera commented on .ruby-version
> +2.7.3
en general mantenemos el 2.7 solo sin patch porque no tiene mucho sentido forzar un patch a todos los que desarrollen en el proyecto. Lo que puedes hacer en local es usar rbenv-alias o sino crear un link simbólico de nombre 2.7 desde tu ruby 2.7.3 en la misma carpeta donde están todos

2021-04-30 17:10 UTC, rjherrera approved these changes

2021-05-01 22:24 UTC, fncabrera requested changes
Muy buena pega! Hermoso lo mágico de power-api jajaja
QA bien, algunos comentarios:
1. En el post y patch del ingredients, en swagger, estaría bueno poner un ejemplo de lo que se envía en el body (así como lo tienen las rutas de user)
2. Es normal que el detail que retorna el delete cuando no encuentra el ingrediente sea esto? 
![image](https://user-images.githubusercontent.com/30879712/116796411-2bbe8300-aaaa-11eb-965c-5754b9471c64.png)
3. Creo que sería bueno ordenar la documentación de swagger (quizás hacerlo en otra PR no más), pero que por ej las rutas estén divididas por modelos para que sea más ordenado
![image](https://user-images.githubusercontent.com/30879712/116796437-66c0b680-aaaa-11eb-94e1-da9e71c16283.png)
4. Está bien que se muestre esto? No veo que aporta
![image](https://user-images.githubusercontent.com/30879712/116796444-7809c300-aaaa-11eb-850e-624354218e61.png)

2021-05-02 00:06 UTC, monkeyci commented on spec/swagger/v1/schemas/ingredient_schema.rb
> +    measure: { type: :string, example: 'Some measure', 'x-nullable': true },
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInHashLiteral: Avoid comma after the last item of a hash.

2021-05-02 00:06 UTC, monkeyci commented on spec/swagger/v1/schemas/ingredient_schema.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLines: Extra blank line detected.

2021-05-02 00:07 UTC, cacosandon commented
> Muy buena pega! Hermoso lo mágico de power-api jajaja
> QA bien, algunos comentarios:
> 
> 1. En el post y patch del ingredients, en swagger, estaría bueno poner un ejemplo de lo que se envía en el body (así como lo tienen las rutas de user)
> 2. Es normal que el detail que retorna el delete cuando no encuentra el ingrediente sea esto? (también en el get /ingredient/:id)
>    ![image](https://user-images.githubusercontent.com/30879712/116796411-2bbe8300-aaaa-11eb-965c-5754b9471c64.png)
> 3. Creo que sería bueno ordenar la documentación de swagger (quizás hacerlo en otra PR no más), pero que por ej las rutas estén divididas por modelos para que sea más ordenado
>    ![image](https://user-images.githubusercontent.com/30879712/116796437-66c0b680-aaaa-11eb-94e1-da9e71c16283.png)
> 4. Está bien que se muestre esto? No veo que aporta
>    ![image](https://user-images.githubusercontent.com/30879712/116796444-7809c300-aaaa-11eb-850e-624354218e61.png)

buena pipe!

1. ready
2. pucha eso lo maneja la gema, no me preocuparía por ahora. Le pongo msjes custom más adelante
3. Dale! lo divido cuando esté lista la documentación, porq al generarla se actualiza toodo de nuevo 
4. Sii, es para mostrar los schemas de lo que devolvemos, si vas haciendo click salen los parametros

2021-05-02 00:46 UTC, monkeyci commented on spec/integration/api/v1/ingredients_spec.rb
> +      before do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on line 26).

2021-05-02 15:27 UTC, fncabrera approved these changes
Todo perfect! crack

2021-05-02 17:37 UTC, merged