Add vue i18n
platanus/2021-1-Grupo4-Web pull request #30
Opened 2021-04-30 02:41 UTC by ValentinaAlvarezG

Se agregó i18n a la aplicación para poder manejar los textos de mejor forma y eventualmente poder traducir a otros idiomas. 

# QA
- Correr la app, e ir a `/ingredients`, la vista se debería mostrar normal, los nombres en español, pero considerando que en el código se manejan por detrás con i18n. 

# Falta
- Conexión con el backend así que aún se pasan los datos como props.

2021-04-30 13:08 UTC, MariaJosefinaAlliende reviewed
Bravo!!  👏🏻  Quedó bacán! Te dejé un par de comentarios sobre textos que  aprovecharía de cambiar al tiro

2021-04-30 13:13 UTC, ValentinaAlvarezG commented on app/views/menus/index.html.erb
> +      Menus
Hola! lo iba a hacer, pero en verdad no caché como podía meterle el `$t()`  a un archivo html.erb (porque lo intenté y no lo conseguí) pero además como eso lo tenemos que meter en componentes cuando hagamos esas vistas, en las componentes deberían ir traducidas como se hizo para ingredientes .

2021-04-30 13:25 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +    yesDelete: 'Sí,Eliminar',
Lo iba a hacer así, pero cuando se desplegaba en el botón en la vista con el texto, encontré que ocupaba demasiado espacio ese espacio, por eso lo dejé sin, no sé que opinas tu.

2021-04-30 13:25 UTC, sofiadelano approved these changes

2021-04-30 13:27 UTC, sofiadelano commented on app/javascript/locales/es.js
> +    yesDelete: 'Sí,Eliminar',
Me suena mejor lo que estoy sugiriendo y creo que más adelante vamos a poder arreglar esos detalles de las vistas, pero en verdad no importa tanto

2021-04-30 16:09 UTC, ValentinaAlvarezG commented on app/views/menus/index.html.erb
> +      Menus
De hecho filo, los voy a sacar porque esto hay que hacerlo en las componentes en verdad, lo teníamos pa probar que el side navbar funcionara, pero creo que no tiene sentido

2021-04-30 16:09 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +    yesDelete: 'Sí,Eliminar',
Ahí lo cambié!

2021-04-30 16:59 UTC, MariaJosefinaAlliende commented on app/views/menus/index.html.erb
> +      Menus
Toooooda la razóon!!! Mala mía en no cachar que era un .erb!!! juré que era de vue. Para eso habría que agregar i18n en rails. Así que ignora mi comentario

2021-04-30 17:00 UTC, MariaJosefinaAlliende approved these changes
Suuuper! Seca! ✅

2021-05-01 21:53 UTC, fncabrera requested changes
Muy buena pega!! Te deje algunos comentarios menores para que les eches un 👁️

2021-05-01 21:53 UTC, fncabrera commented on app/javascript/components/base/base-search-component.vue
> +    kind: { type: String, required: true },
Para que es el kind? (que no se ocupa), no será mejor que se llame "type"?

2021-05-01 21:53 UTC, fncabrera commented on app/javascript/components/base/base-table-component.vue
> +          <span class="text-white font-bold">{{ $t(`msg.${modelType}.${attribute}`) }}</span>
buenísimo!

2021-05-01 21:53 UTC, fncabrera commented on app/javascript/packs/application.js
> +import Locales from '../locales/locales.js';
por orden, deja esta linea y la 19 antes de la importación de las componentes vue

2021-05-01 21:53 UTC, fncabrera commented on app/javascript/locales/es.js
> +  msg: {
Es necesario esto que engloba a las demás? Siento que como todo en sí son mensajes/texto no es tan necesario, solo hace más largo el texto al momento de llamarlo

2021-05-01 22:12 UTC, ValentinaAlvarezG commented on app/javascript/components/base/base-search-component.vue
> +    kind: { type: String, required: true },
Es que aún no hacemos nada con el search bar así que filo, lo sacaré no más mientras.

2021-05-01 22:17 UTC, ValentinaAlvarezG commented on app/javascript/packs/application.js
> +import Locales from '../locales/locales.js';
La 19 la tuve que dejar abajo porque o si no me alegaba que los otros import van antes:

![image](https://user-images.githubusercontent.com/26123660/116796297-712e8080-aaa9-11eb-8bce-9d0e5c299a91.png)

2021-05-01 22:22 UTC, ValentinaAlvarezG commented on app/javascript/locales/es.js
> +  msg: {
Mmm supongo que sí, así por lo menos me lo recomendó la niña de platanus, así lo he visto cuando lo he buscado. Porque no sé en verdad si lo dejara como ``export default`` no más todo, no sé si sería un objeto, porque al final estaría exportando muchas cosas distintas, así supongo que exporto un solo objeto que tiene todo :thinking:

2021-05-01 22:26 UTC, fncabrera approved these changes
Todo good, grande! Espera que pase los test/linters de CI y dale merge no más

2021-05-01 22:32 UTC, merged