Frontend login
platanus/2021-1-Grupo4-Web pull request #33
Opened 2021-05-02 22:12 UTC by ValentinaAlvarezG

# Contexto

Crear el manejo de sesiones para la aplicación usando tanto frontend como la API del backend. 

# Lo que hice

- Crear las vistas de register y login
- Al registrar, crear un usuario
- Al iniciar sesión, guardar el token enviado por la API
- Modificar el top navbar para tener acceso al SignUp y SignIn (cuando no está logeado) y al SignOut (cuando está logeado)

# QA

- Correr la app
- Ir a /users/sign/up
- Crear un usuario. Si la response por parte de la API está ok, se crea el usuario y se redirige a inicio de sesión. Si hubo algún error se muestra un mensaje en rojo indicando que hubo un error.
- Si todo salió bien en el punto anterior, se redirige a Inicio de sesión por lo que se puede iniciar sesión con el usuario recién creado. Si hubo algún error se muestra un mensaje en rojo indicando que hubo un error. Si todo sale bien con el inicio de sesión se redirige a /ingredients. Como hay un ususario logeado, en el top navbar ya no se ven las opciones de 'Iniciar Sesión' o 'Registrarse', y ahora se muestra el de 'Cerrar Sesión'. En cualquiera de las páginas se va a seguir viendo solo la opción de 'Cerrar Sesión' porque el usuario está logeado.
- Si se hace click en 'Cerrar sesión', se redirige a 'Home' (donde aún no tenemos nada), y vuelven las opciones de 'Iniciar Sesión' y 'Registrarse' y se va la de 'Cerrar Sesión', vemos que esto pasa en cualquier página. 

# Falta
- Adaptar la vista al estilo definitivo
- Mejorar la usabilidad y validaciones por parte del front (mensajes sobre el largo de la contraseña, ser más descriptivo con los errores ocurridos, etc...) 
- Negar el acceso a rutas de inicio de sesión o de registrarse en caso de que el usuario ya esté logeado. 
- Que los ingredientes que se muestren sean solo de ese usuario (hacer las conexión e ingredientes con el backend)
- Restringir el acceso a /ingredients (y a todas las demás páginas) a usuarios no logeados.

2021-05-03 20:57 UTC, difernandez requested changes
Principalmente me gustaría que vean lo de extraer las llamadas a api a archivos.

Un par de comentarios aparte si:

- Ojo con el manejo de la rama. No se bien que pasó, pero hay varios commits duplicados como con los mismos cambios. Cuando se necesitan hacer cambios en una branch de una feature (no master ni production) muchas veces usamos rebase, les dejo [este post que escribió un compañero](https://plata.news/blog/manteniendo-la-historia-limpia-usando-git-rebase/) al respecto. Dejar los commits de este pr ordenados puede ser mucha pega pero para que lo tengan en cuenta para los siguientes
- Se generaron muchas vistas automáticamente con devise. Trataría de dejar solo lo que se va a usar para no ir acumulando cosas innecesarias

2021-05-03 20:57 UTC, difernandez commented on app/javascript/components/users/register-component.vue
> +    },
- Esto no debería quedar con el host, no funcionaría ni en local, ni en producción, ni si cambian el dominio. Pueden poner solo `/api/v1/users/registrations`, eso llama a la request en el mismo host que está el front, y como back y front están donde mismo no habría problema
- Ideal si dejan todas las llamadas centralizadas en una carpeta/archivos. Les recomendaría tener una carpeta `api` dentro de `javascript`, y en esa carpeta crean un archivo para cada "recurso" (por ejemplo, `users.js`, `ingredients.js`). En ese archivo exportarían todos las llamadas axios de ese recurso, y se importa de ahí cuando se necesite en un componente (o store si tienen o van a tener). En este caso podrían definir un `register(user)`, donde recibe como parámetro el user que le pasarían a axios. Tendrían que retornar la promesa para que acá funcione el then/catch

2021-05-03 20:57 UTC, difernandez commented on app/javascript/components/layout/top-navbar-component.vue
> +      </a>
También puedes agrupar varias cosas usando un `template` con el v-if:
```
<template v-if="logged">
  <a>...</a>
  <a>...</a>
</template>
```
así también puedes fácil usar `v-else` para el caso contrario en el botón que sigue

2021-05-03 20:57 UTC, difernandez commented on app/javascript/components/users/login-component.vue
> +    },
idem lo de extraer las llamadas a la api y no poner el host

2021-05-03 20:57 UTC, difernandez commented on app/javascript/components/users/register-component.vue
> +          this.status = 400;
En vez de setear esto siempre a 400 hardcodead y solo usarlo para el v-if de arriba, podrían usar si es que existe o no un `error`

2021-05-04 20:22 UTC, sofiadelano approved these changes
Está muy bueno!! Más adelante le seguimos arreglando el diseño, pero por ahora está perfecto para poder hacer un manejo de usuario básico y poder crear ingredientes y esas cosas.

2021-05-05 00:22 UTC, cacosandon approved these changes
te dejé un mini comentario aparte de lo que comentó difernandez

elimina las vistas que no usamos de devise. Puedes decirle a rails cuál específicamente generar pa la otra! Por ej. `rails generate devise:views -v registrations confirmations`

2021-05-05 00:22 UTC, cacosandon commented on app/javascript/components/layout/top-navbar-component.vue
> +      localStorage.setItem('token', '');
```suggestion
      localStorage.removeItem('token');
```
creo que debería funcionar

2021-05-06 01:41 UTC, ValentinaAlvarezG commented on app/javascript/components/layout/top-navbar-component.vue
> +      localStorage.setItem('token', '');
buena!

2021-05-06 13:48 UTC, difernandez approved these changes
buena!

2021-05-06 14:38 UTC, merged