Frontend/all recipes
platanus/2021-1-Grupo4-Web pull request #34
Opened 2021-05-03 20:48 UTC by sofiadelano

# Contexto

Crear vista principal de las rectas

# Lo que hice

- Crear vista principal de recetas en index.html.erb, la cual por ahora recibe un par de recetas harcodeadeas. 
- Crear componentes necesarias dentro de components/recipes/index
- Agregar i18n a la vista principal de recetas

# QA

- Correr la app
- Ir a /recipes

# Falta
- Dar funcionalidad a la vista, y que los botones funcionen.
- Conectar con backend
- Hacer la vista _responsive_

2021-05-03 22:05 UTC, iaacosta requested changes
Buena! Les quedó igualita la UX 👏🏻

Te dejé unos comentarios! Cuéntame que opinas

2021-05-03 23:24 UTC, sofiadelano commented on app/javascript/components/recipes/index/base-component.vue
> +    <div class="flex flex-row justify-between items-center p-0 static h-8 flex-none order-0 flex-grow-0 mt-1 mb-4">
Perfecto!!

2021-05-04 19:04 UTC, iaacosta approved these changes

2021-05-04 21:31 UTC, fncabrera approved these changes
QA perfect, grande sofi 🚀

2021-05-04 21:49 UTC, merged