BASE[#40] feat(recipe-steps): add recipe steps to api
platanus/2021-1-Grupo4-Web pull request #41
Opened 2021-05-07 15:01 UTC by cacosandon

Base #40

### Contexto
En el PR #39 creé el modelo `RecipeSteps` con toda la lógica de pasos en una receta para reemplazar el atributo `instructions`que eliminé en el PR #40. Ahora toca integrarlo a la API 🙂 

### Qué hice

Agregué el controlador de `RecipeStep` que permite crear, editar y eliminar. No es necesario el index o show porque viene integrado en el serializer de `Recipe`.

Agregué las rutas a swagger

### QA

Probar las tres nuevas rutas:
![image](https://user-images.githubusercontent.com/30879716/117467803-0904f200-af22-11eb-80e3-00d1349e731d.png)

Deberían seguir la lógica mencionada en #39, donde si eliminas un paso o lo cambias de posición entonces se actualiza la posición de los demás

2021-05-07 15:32 UTC, agomezcampero requested changes
Creo que sería bueno dejar las rutas todas en el mismo lugar.

Para manejar el orden de los recipe steps podrían usar la gema [ranked_model](https://github.com/mixonic/ranked-model), después te va a permitir hacer los cambios de orden mucho más fácil.

`recipe_step.update(row_order_position: 2)` (y va a quedar en la tercera posición o segunda si partimos de 0)

2021-05-07 15:36 UTC, cacosandon commented on config/routes.rb
> +      end
más que nada porq ambas usan el id no más, no es necesario el id de la receta. pero quizás sería weno dejarlas todas juntas no más

2021-05-07 15:38 UTC, cacosandon commented
> Creo que sería bueno dejar las rutas todas en el mismo lugar.
> 
> Para manejar el orden de los recipe steps podrían usar la gema [ranked_model](https://github.com/mixonic/ranked-model), después te va a permitir hacer los cambios de orden mucho más fácil.
> 
> `recipe_step.update(row_order_position: 2)` (y va a quedar en la tercera posición o segunda si partimos de 0)

jajaja en la #39 hice yo la lógica. ocupo la gema o lo dejo?

2021-05-07 15:45 UTC, agomezcampero commented
> jajaja pucha en la #39 hice yo la lógica, ni caché la gema. la ocupo o lo dejo?

Yo la ocuparía, tiene un par de cosas buenas de performance para no tener que modificar tantos modelos al momento de cambiar. Si están con muchas cosas, lo podemos patear para el segundo ciclo

2021-05-07 15:49 UTC, cacosandon commented
> > jajaja pucha en la #39 hice yo la lógica, ni caché la gema. la ocupo o lo dejo?
> 
> Yo la ocuparía, tiene un par de cosas buenas de performance para no tener que modificar tantos modelos al momento de cambiar. Si están con muchas cosas, lo podemos patear para el segundo ciclo

okas, hago todos los cambios en un rato!

2021-05-07 19:33 UTC, agomezcampero approved these changes
Lo veo bien, la gema y migración están en otro pr verdad?

2021-05-07 21:36 UTC, cacosandon commented
> Lo veo bien, la gema y migración están en otro pr verdad?

yes, quedó en la primera pr

2021-05-08 14:12 UTC, sofiadelano approved these changes
No soy muy experta en esto, pero se ve bien!

2021-05-12 16:35 UTC, fthurtado approved these changes
Se ve todo bien 🚀

2021-05-12 23:03 UTC, merged