Validations
platanus/2021-1-Grupo4-Web pull request #43
Opened 2021-05-09 19:59 UTC by Arodriguez14

### Contexto ###

- Se creo un landing Page para que no aparezca la pagina de inicio de Ruby on Rails.
- Se negó el acceso a rutas cuando no se ha iniciado sesión. Ej: No poder acceder a _/ingredients_ si no se ha iniciado sesión.
- Se arreglaron errores del log in y sign up que habian al cerrar sesión.

### QA ### 
Ingresar a http://localhost:3000 y ver el landing page. Luego cambiar el path a http://localhost:3000/recipes y debería aparecer el formulario de log in en vez de ir a las recetas (lo mismo con el resto de los path). Luego hacer log in y ahi debería ingresar a las vistas. 
Para probar el manejo de cerrar sesión, hay que registrar un usuario, luego cerrar sesión y finalmente ingresar en el log in con el usuario recién creado.

2021-05-09 20:00 UTC, monkeyci commented on app/javascript/components/landing-page.vue
> +<div>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 2 spaces but found 0 spaces  vue/html-indent

2021-05-09 20:00 UTC, monkeyci commented on app/javascript/components/landing-page.vue
> +</div>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 2 spaces but found 0 spaces  vue/html-indent

2021-05-09 20:00 UTC, monkeyci commented on app/javascript/components/landing-page.vue
> +</script>
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Newline required at end of file but not found        eol-last

2021-05-10 14:39 UTC, aescobar4 commented on app/views/home/index.html.erb
> +    <landing-page />
Esto no debería tener 2 espacios?

2021-05-10 14:52 UTC, aescobar4 approved these changes
Todo bien! Le arreglé un detalle del mono con unos commit directos

2021-05-10 14:59 UTC, Arodriguez14 commented on app/javascript/api/users.js
> +const CSRFToken = tokenEl && tokenEl.getAttribute('content');
Toma el token para que los post de User deban hacerse únicamente desde la app y no desde otro lado (postman por ejemplo)

2021-05-10 14:59 UTC, Arodriguez14 commented
> Todo bien! Le arreglé un detalle del mono con unos commit directos

Gracias !

2021-05-10 15:13 UTC, aescobar4 commented on app/javascript/api/users.js
> +const CSRFToken = tokenEl && tokenEl.getAttribute('content');
Aaah perfect, gracias

2021-05-10 16:29 UTC, difernandez requested changes
Dejo unos comentarios! En particular creo que lo más importante es lo del `<landing-page />`

2021-05-10 16:29 UTC, difernandez commented on app/javascript/api/users.js
> +        'X-CSRF-Token': CSRFToken,
Para las cosas con api no deberían necesitar el CSRF token, pueden agregar `skip_before_action :verify_authenticity_token` al controlador base de la api

2021-05-10 16:29 UTC, difernandez commented on app/controllers/api/v1/users/registrations_controller.rb
> +    sign_in user
Con esto se mezcla un poco las dos maneras de autenticar que tienen. Por ejemplo, si se registran desde la app mobile con este endpoint, el `sign_in user` no haría sentido para la app.

Idealmente, el sign_in, cómo es de devise para las vistas no-api, se debería hacer en un controlador no api. Como está esta mezcla entre autenticación por token y por devise, es medio enredado cómo sería la mejor implementación, pero se los menciono por si lo pueden ver más adelante

2021-05-10 16:29 UTC, difernandez commented on app/controllers/api/v1/users/registrations_controller.rb
>      render json: user, serializer: Api::V1::UserSerializer, status: :created
Fuera del scope de este PR, y no espero que se cambie ahora, pero se los menciono para futuro. En los controllers deberían usar `respond_with` en vez de `render json:`. Esto hace que se usen los responders y se pase por los concerns de errores definidos en Power Api. También les ahorra tener que poner el `status: :created`.

En este caso en particular sería `respond_with user, serializer: Api::V1::UserSerializer`

2021-05-11 01:26 UTC, Arodriguez14 commented on app/javascript/api/users.js
> +        'X-CSRF-Token': CSRFToken,
Hola! Perdón pero no entendí mucho esto. Eliminé los headers y agrege el skip_before_action pero no funciona. Feliz si me puedes explicar más!

2021-05-11 22:05 UTC, fncabrera approved these changes
QA good, creo que sería bueno en el home meter la componente de la side-navbar (así podemos navegar hacia lo que queramos desde el home y no tener que entrar por la ruta)

2021-05-12 01:34 UTC, Arodriguez14 commented
> QA good, creo que sería bueno en el home meter la componente de la side-navbar (así podemos navegar hacia lo que queramos desde el home y no tener que entrar por la ruta)

Buen comentario. Deje que el home sea solo para log in y log out y que la primera pagina que aparezca al iniciar sesión sea /ingredients. Eso era lo que habiamos conversado. Gracias Pipe!

2021-05-12 01:36 UTC, Arodriguez14 commented on app/javascript/api/users.js
> +        'X-CSRF-Token': CSRFToken,
Hablé con Agustín y me comentó que lo dejemos asi por mientras y lo arreglemos mas adelante. Espero la aprobación o algún otro comentario para poder hacer merge! Gracias Diego!

2021-05-12 13:51 UTC, difernandez commented on app/javascript/api/users.js
> +        'X-CSRF-Token': CSRFToken,
oh disculpa vi tarde este comentario!! Me parece bien dejarlo para después! Te explico igual un poco a que me refería por si sirve:

El CSRF token es para asegurar que las requests al backend se hacen desde el mismo sitio. Pero para la api, cómo van a tener mobile que va a hacer requests desde afuera del sitio, no lo necesitarían. Entonces se puede apagar la verificación de esa token agregando `skip_before_action :verify_authenticity_token` al controller del que heredan lo controlers de api. Esto es la contraparte a `protect_from_forgery`, si no te funcionó puede que esté eso seteado en un lado

2021-05-12 13:53 UTC, difernandez approved these changes

2021-05-12 19:31 UTC, merged

2021-05-12 19:32 UTC, Arodriguez14 commented on app/javascript/api/users.js
> +        'X-CSRF-Token': CSRFToken,
Perfect. Gracias!!