Frontend backend recipes show
platanus/2021-1-Grupo4-Web pull request #45
Opened 2021-05-12 01:08 UTC by sofiadelano

# Contexto

Conectar con el backend el index y show de recipes

# Lo que hice

- Crear app/javascript/api/recipes
- Agregar al archivo anterior la función getRecipes par obtener las recetas pertenecientes a un cierto usuario
- Agregar al archivo anterior la función getRecipe par obtener la información correspondiente a una receta en específico perteneciente a un cierto usuario
- Agregar al archivo anterior la función deleteRecipe para eliminar una receta perteneciente a un cierto usuario
- Conectar la vista /recipes con recipes/{id} al apretar cierta receta y devuelta al apretar el botón con el ícono para ir hacia atrás
- Implementar el get de recipes en la vista /recipes para obtener las recetas correspondientes al usuario loggueado
- Implementar el get de una recipe en la vista /recipe/{id} para obtener la información de la receta en cuestión correspondiente al usuario loggueado
- Implementar el delete de una recipe en la vista /recipe/{id} para eliminar la receta en cuestión correspondiente al usuario loggueado

# QA

- Correr la app
- Registrarse en /users/sign_up e iniciar sesión en users/sign_in
- Agregar recetas de manera local (puede ser mediante postman en la ruta "localhost:3000/api/v1/recipes"
- Ir a /recipes
- Apretar una receta en el botón a la derecha del precio para ir a ver esa receta
- Volver hacia atrás con el botón de retroceder
- Eliminar una receta con el botón correspondiente en la vista de la receta

# Falta
- Dar funcionalidad a los popups  de filtros
- Conectar con _backend_ para que realmente filtren
- Implementar el buscador
- Como no está lista la vista para crear/editar una receta no funciona el botón crear receta
- No está implementado el agregar una receta a partir de ingredientes, por lo que los ingredientes están harcodeados, al igual que los precios (ya que estos dependen de los precios de los ingredientes)

2021-05-12 16:14 UTC, ValentinaAlvarezG approved these changes
En general veo todo super bien!

2021-05-13 01:03 UTC, iaacosta requested changes
Buena! Mejoró caleta de lo que vi de la PR cerrada, te dejé igual unos comentarios que encontré que creo que se pueden mejorar, cualquier duda o discusión feliz de hablarlo!

2021-05-13 01:03 UTC, iaacosta commented on app/javascript/components/recipes/show/base-component.vue
> +      this.error = '';
Estos no están definidos en el `data`, es mejor que si lo estén para que al lector le quede claro que existe :eyes:

Me queda la duda también de por qué está el `status`, para el futuro?

2021-05-13 16:16 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/index/base-price-recipe.vue
> +    </button>
Bacán! en verdad no cachábamos como pasarle una variable en el href pq no nos funcionaba. Pero ahí con lo que pusiste me di cuenta de que teníamos que poner los dos puntos y las comillas dobles. Gracias!

2021-05-13 16:19 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/index/base-component.vue
> +      recipeToDelete: {},
tienes razón, en verdad no los necesitamos en esta componente!

2021-05-13 16:20 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/index/base-component.vue
> +      status: '',
Los status los estamos guardando por si después necesitamos mostrar algún mensaje más descriptivo sobre la respuesta de la API.

2021-05-13 16:25 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/show/base-component.vue
> +      this.error = '';
Aquí lo mismo que en el otro, lo tenemos guardado por si vamos a necesitar mostrar mensajes más descriptivos o algo así, o tu crees que en verdad son innecesarios?

2021-05-13 16:32 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/index/base-recipes.vue
> +        :id="recipe.id"
Tienes toda la razón! bacan, gracias!!

2021-05-13 16:44 UTC, monkeyci commented on app/javascript/components/ingredients/base-component.vue
> +    console.log(localStorage.getItem('token'));
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-05-13 18:38 UTC, iaacosta approved these changes
Quedaron dos temas pendientes, se las dejo aprobada porque son detalles, pero ideal que los aborden en otra PR si es que no los cambian ahora

2021-05-13 18:38 UTC, iaacosta commented on app/javascript/components/recipes/show/base-component.vue
> +      this.error = '';
Lo del error lo encuentro perfect! Es bacán dar el feedback al usuario si algo sale mal

Lo del `status` creo que no aporta, porque el feedback si todo sale bien son las recetas mismas, entonces es medio redundante.

Yo borraría los `status`, pero si andan apuradas con esta PR lo dejaría como un refactor!

2021-05-13 18:38 UTC, iaacosta commented on app/views/recipes/show.html.erb
> +    <recipe-show :recipe-id = <%= params[:id]%>></recipe-show>
Que no se les pierda esto! De repente pasan bugs medios raros en Rails con HTML mal escrito.

Si andan apuradas, mejórenlo en otra PR, pero que no se les pase luego porfa 🙏🏻

2021-05-13 18:39 UTC, merged