Frontend/recipe modal v2
platanus/2021-1-Grupo4-Web pull request #66
Opened 2021-05-26 22:54 UTC by miortiz1

# Lo que se hizo
Se creo un modal con componentes para buscar entre todos los ingredientes que uno posee, seleccionarlos y luego añadirlos a los ingredientes de una receta
#QA
En recipes/new al apretar el boton de "buscar ingredientes" se debe abrir un modal. De ahi deberian poder seleccionar agregar ingredientes con el "+" y al apretar "Agregar estos debiesen ser agregados a los ingredientes de la receta.
![image](https://user-images.githubusercontent.com/37181021/119740844-9917c680-be52-11eb-8746-c0597ee39d4a.png)
![image](https://user-images.githubusercontent.com/37181021/119740878-a5038880-be52-11eb-9fda-554860dbd44d.png)
# Falta
- Aunque no es posible seleccionar el mismo ingrediente 2 veces, si es posible añadirlo dos veces a la receta si se abre el modal 2 veces.
- Conectar con backend para mostrar todos los ingredientes que posee el usuario al momento de buscar mas ingredientes.

2021-05-26 22:55 UTC, monkeyci reviewed
Remaining comments which cannot be posted as a review comment to avoid GitHub Rate Limit

<details>
<summary>eslint</summary>

[app/javascript/components/recipes/new/search-ingredient-list.vue|39 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L39) Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|40 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L40) Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|40 col 25|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L40)   Trailing spaces not allowed                                                  no-trailing-spaces
[app/javascript/components/recipes/new/search-ingredient-list.vue|41 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L41) Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|41 col 23|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L41) Expected to be enclosed by double quotes                                     vue/html-quotes
[app/javascript/components/recipes/new/search-ingredient-list.vue|42 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L42) Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|43 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L43) Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|44 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L44) Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|53 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L53)   Expected 1 empty line after import statement not followed by another import  import/newline-after-import
[app/javascript/components/recipes/new/search-ingredient-list.vue|57 col 49|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L57)   Missing trailing comma                                                       comma-dangle
[app/javascript/components/recipes/new/search-ingredient-list.vue|61 col 7|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L61)   Identifier 'current_page' is not in camel case                               camelcase
[app/javascript/components/recipes/new/search-ingredient-list.vue|62 col 44|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L62)   Missing trailing comma                                                       comma-dangle
[app/javascript/components/recipes/new/search-ingredient-list.vue|63 col 6|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L63)   Missing semicolon                                                            semi
[app/javascript/components/recipes/new/search-ingredient-list.vue|73 col 7|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L73)   Expected newline before return statement                                     newline-before-return
[app/javascript/components/recipes/new/search-ingredient-list.vue|75 col 4|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L75)   Missing trailing comma                                                       comma-dangle
[app/javascript/components/recipes/new/search-ingredient-list.vue|76 col 2|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/search-ingredient-list.vue#L76)   Missing semicolon                                                            semi
[app/javascript/components/recipes/new/selected-ingredients.vue|4 col 9|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L4)   Trailing spaces not allowed                            no-trailing-spaces
[app/javascript/components/recipes/new/selected-ingredients.vue|5 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L5) Expected indentation of 6 spaces but found 4 spaces    vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|14 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L14) Expected indentation of 8 spaces but found 7 spaces    vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|17 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L17) Expected indentation of 10 spaces but found 14 spaces  vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|18 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L18) Expected indentation of 10 spaces but found 14 spaces  vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|19 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L19) Expected indentation of 8 spaces but found 12 spaces   vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|37 col 28|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L37)   Missing space before opening brace                     space-before-blocks
[app/javascript/components/recipes/new/selected-ingredients.vue|39 col 6|](http://github.com/platanus/2021-1-Grupo4-Web/blob/8121034c2c219c15299cb8fffdd40a2fd5085d7d/app/javascript/components/recipes/new/selected-ingredients.vue#L39)   Missing trailing comma                                 comma-dangle
[app/javascript/components/recipes/new/selected-ingredients.vue|41 col 2|](http://github.com/platanus/2021-1-Grupo4-Web/blob [...]

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> + <template>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 0 spaces but found 1 space                                vue/html-indent

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> + <template>
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                       no-trailing-spaces

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +      @click="clickButton"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 4 spaces but found 6 spaces                               vue/html-indent

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +  > + </button>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<button>`), but no line breaks found    vue/multiline-html-element-content-newline

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +  > + </button>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</button>`), but no line breaks found  vue/multiline-html-element-content-newline

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  A space is required after '{'                                                     object-curly-spacing

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before value for key 'required'                                     key-spacing

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  A space is required before '}'                                                    object-curly-spacing

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                            comma-dangle

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                                 semi

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                                 semi

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          <search-ingredient-list
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        <selected-ingredients
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        />
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    </base-modal>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</div>`), but 2 line breaks found  vue/multiline-html-element-content-newline

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    BaseModalComponent,
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  The "BaseModalComponent" component has been registered but not used           vue/no-unused-components

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                             semi

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    toggleAddIngredientModal(){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredient(object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +      var i;
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Unexpected var, use let or const instead                                      no-var

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        if (this.selectedIngredients[i] == object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected '===' and instead saw '=='                                           eqeqeq

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        if (this.selectedIngredients[i] == object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredientstoRecipe(){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    deleteIngredient(index){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                        comma-dangle

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      <input
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Disallow self-closing on HTML void elements (<input/>)                       vue/html-self-closing

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +          <th
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                  no-trailing-spaces

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +          <th/>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected a space before '/>', but not found                                  vue/html-closing-bracket-spacing

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +          class="content-center py-2">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 12 spaces but found 10 spaces                        vue/html-indent

2021-05-26 22:55 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +          class="content-center py-2">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing bracket, but no line breaks found       vue/html-closing-bracket-newline

2021-05-26 23:13 UTC, monkeyci reviewed
Remaining comments which cannot be posted as a review comment to avoid GitHub Rate Limit

<details>
<summary>eslint</summary>

[app/javascript/components/recipes/new/selected-ingredients.vue|39 col 6|](http://github.com/platanus/2021-1-Grupo4-Web/blob/90d0fde0caa5523104a9df9dd909dd3f3041b587/app/javascript/components/recipes/new/selected-ingredients.vue#L39)   Missing trailing comma                                 comma-dangle
[app/javascript/components/recipes/new/selected-ingredients.vue|41 col 2|](http://github.com/platanus/2021-1-Grupo4-Web/blob/90d0fde0caa5523104a9df9dd909dd3f3041b587/app/javascript/components/recipes/new/selected-ingredients.vue#L41)   Missing semicolon                                      semi
[app/javascript/packs/application.js|51 col 15|](http://github.com/platanus/2021-1-Grupo4-Web/blob/90d0fde0caa5523104a9df9dd909dd3f3041b587/app/javascript/packs/application.js#L51) Property name "addButtonComponent" is not PascalCase  vue/component-definition-name-casing
</details>

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    +
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Trailing spaces not allowed                    no-trailing-spaces

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>A space is required after '{'                  object-curly-spacing

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing space before value for key 'required'  key-spacing

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>A space is required before '}'                 object-curly-spacing

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma                         comma-dangle

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon                              semi

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon                              semi

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +           <p class="content-center text-center ml-2 font-semibold">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             <add-button
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             <add-button
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                  no-trailing-spaces

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              :object=ingredient
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              :object=ingredient
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected to be enclosed by double quotes                                     vue/html-quotes

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              @add-ingredient="addIngredient"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             />
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +           </p>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +import addButton from './add-button.vue';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected 1 empty line after import statement not followed by another import  import/newline-after-import

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +    ingredients: { type: Array, required: true }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                       comma-dangle

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      current_page: 0,
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Identifier 'current_page' is not in camel case                               camelcase

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      header: ['name', 'price', 'quantity']
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                       comma-dangle

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                            semi

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      return parsedElements;
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected newline before return statement                                     newline-before-return

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +  }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                       comma-dangle

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                            semi

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    <div
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                            no-trailing-spaces

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    class="flex p-4 grid grid-cols-2 items-center justify-between "
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 6 spaces but found 4 spaces    vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +       @click="deleteIngredient(index)"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 7 spaces    vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +              class="w-4 h-4"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 10 spaces but found 14 spaces  vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +              src="../../../../assets/images/cancel-svg.svg"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 10 spaces but found 14 spaces  vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +            >
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 12 spaces   vue/html-indent

2021-05-26 23:13 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    deleteIngredient(index){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                     space-before-blocks

2021-05-27 00:03 UTC, aescobar4 commented
Quizás sería bueno q revises todos los comentarios del mono, porque es un poco difícil revisar los archivos con tantos comentarios. No sé si la tienes, pero hay una extensión de VSCode que para ESLint (creo que se llama así), te reclama por todos los errores y te los puede corregir automáticamente, así no vas a tener muchos problemas de nuevo con eso

2021-05-27 03:53 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    +
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Trailing spaces not allowed  no-trailing-spaces

2021-05-27 03:53 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    deleteIngredient(index){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing space before opening brace        space-before-blocks

2021-05-27 03:53 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      <input
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Disallow self-closing on HTML void elements (<input/>)  vue/html-self-closing

2021-05-27 03:53 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma  comma-dangle

2021-05-27 03:53 UTC, monkeyci commented on app/javascript/packs/application.js
> +Vue.component('addButtonComponent', addButtonComponent);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Property name "addButtonComponent" is not PascalCase  vue/component-definition-name-casing

2021-05-27 13:34 UTC, aescobar4 commented on app/javascript/components/recipes/new/container.vue
> +    element: { type: String, default: () => ('') },
Es necesario tener 2 props de tipo String? Me acuerdo que no siempre usaba text, así que no sé si element es necesaria

2021-05-27 13:53 UTC, aescobar4 commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredientstoRecipe() {
Sólo para entender como funciona, si yo abro el modal, agrego ingredientes, cierro el modal y después lo vuelvo a abrir, la lista del nuevo modal me va a aparecer vacía? En ese caso podrían haber ingredientes repetidos? Creo que podría pasar eso por como está armado o no?

2021-05-27 13:57 UTC, aescobar4 commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    <span class="flex content-center justify-center">Ingredientes seleccionados</span>
No debería estar con el i18n?

2021-05-27 13:59 UTC, aescobar4 commented on app/javascript/packs/application.js
> +import AddButton from '../components/recipes/new/add-button.vue';
En cuantas componentes estás usando este AddButton? Me fijé que la usabas en una (`search-ingredient-list`) y que la importabas localmente en esa, pero no la vi en otras. Quizás no es necesario importarla globalmente.

2021-05-27 18:33 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredientstoRecipe() {
Lo arregle en otra pr. Dentro del modal no pueden haber ingredientes repetidos y en los ingredientes de la recenta en otra pr tampoco se pueden repetir. Si cierras el modal con el boton verde al abrirlo de neuvo estara vacio, pero si solo le das a cerrar, estarán los ingredientes que tenias antes

2021-05-27 19:23 UTC, miortiz1 commented on app/javascript/components/recipes/new/container.vue
> +    element: { type: String, default: () => ('') },
Element se ocupa para el parsed, pq al final es un json, entonces yo creo que si es necesaria o no? De lo que entendi te metiste en 2 casos para container, si es un ingrediente o un step(?

2021-05-27 19:44 UTC, monkeyci commented on app/javascript/locales/es.js
> +      selected: 'Ingredientes seleccionados'
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma  comma-dangle

2021-05-27 20:22 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredient(object) {
arreglado

2021-05-27 20:22 UTC, miortiz1 commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    <span class="flex content-center justify-center">Ingredientes seleccionados</span>
arreglado

2021-05-27 20:22 UTC, miortiz1 commented on app/javascript/packs/application.js
> +import AddButton from '../components/recipes/new/add-button.vue';
Done

2021-05-31 14:29 UTC, aescobar4 commented on app/javascript/components/recipes/new/container.vue
> +    element: { type: String, default: () => ('') },
Claro, container se usa para steps o ingredientes, pero al principio ingredientes era object. A lo que voy, es que si pasas el ingrediente como string y no estás usando la prop text, quizás no es necesario element. Si la encuentras necesaria, úsala igual no más

2021-05-31 14:33 UTC, aescobar4 approved these changes
Todo en orden!

2021-05-31 19:17 UTC, fncabrera reviewed
El funcionamiento se ve bien en general, good QA!

Eso si, creo que falta gestionar para todas las vista, mensajes que se despliegen por ej arriba para los mensajes de warnings (por ej si no metía nombre de la receta creo, sale un pop up del navegador con el mensaje de que eso falta) y sería más bonito algo tipo 
![image](https://user-images.githubusercontent.com/30879712/120233148-24160980-c223-11eb-9e0d-6c6f520c991b.png)
Igual lo debería para otra PR, hablemoslo el jueves 👌 

La conexión a backend la harás despues de mergear con la otra PR?

2021-05-31 21:26 UTC, miortiz1 commented
> El funcionamiento se ve bien en general, good QA!
> 
> Eso si, creo que falta gestionar para todas las vista, mensajes que se despliegen por ej arriba para los mensajes de warnings (por ej si no metía nombre de la receta creo, sale un pop up del navegador con el mensaje de que eso falta) y sería más bonito algo tipo
> ![image](https://user-images.githubusercontent.com/30879712/120233148-24160980-c223-11eb-9e0d-6c6f520c991b.png)
> Igual lo debería para otra PR, hablemoslo el jueves 👌
> 
> La conexión a backend la harás despues de mergear con la otra PR?

Okay! el jueves lo vemos. 
La conexion a backend esta en la pr 67 👌

2021-05-31 22:00 UTC, AndresGarciadelaHuerta requested changes
Está bueno, congrats! 🚀  Te dejé un par de cambios para acortar y dejar más legibles algunos métodos, pero en general se ve bien 👏

2021-06-01 15:03 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +      for (let i = 0; i < this.objects.length; i++) {
en la siguiente pr se elimina este computed :)

2021-06-01 15:06 UTC, miortiz1 commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +    parsedElements() {
Tambien se elimina este computed en la siguiente pr

2021-06-01 15:26 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredientstoRecipe(){
cambiado

2021-06-01 15:26 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +      this.selectedIngredients.push(object);
cambiado

2021-06-01 16:53 UTC, AndresGarciadelaHuerta approved these changes
👏

2021-06-01 18:15 UTC, merged