Frontend/modal backend
platanus/2021-1-Grupo4-Web pull request #67
Opened 2021-05-27 02:26 UTC by miortiz1

# Lo que se hizo
Se conecto con los ingredientes que tiene un usuario para que los liste en el modal y tener la opcion de agregarlos a la receta. Ademas se aprovechó de arreglar el que se podian agregar ingredientes repetidos.
# QA
En recipes/new al apretar el boton de "buscar ingredientes" se debe abrir un modal y deberan aparecer los ingredientes que ese usuario tiene disponible. Al añadir uno y luego reabrir el modal e intentar agregarlo de nuevo, este no se deberia ver duplicado en la receta.
![image](https://user-images.githubusercontent.com/37181021/119756274-51546780-be71-11eb-90ea-8646a048826f.png)

# Falta
Hacer la paginacion de los ingredientes en el modal, y hacer scrollable los ingredientes seleccionados.

2021-05-27 02:27 UTC, monkeyci reviewed
Remaining comments which cannot be posted as a review comment to avoid GitHub Rate Limit

<details>
<summary>eslint</summary>

[app/javascript/components/recipes/new/create-recipes.vue|160 col 70|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/create-recipes.vue#L160)   Missing space before opening brace                                            space-before-blocks
[app/javascript/components/recipes/new/create-recipes.vue|162 col 13|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/create-recipes.vue#L162)   Expected newline before return statement                                      newline-before-return
[app/javascript/components/recipes/new/create-recipes.vue|165 col 22|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/create-recipes.vue#L165)   Missing space before opening brace                                            space-before-blocks
[app/javascript/components/recipes/new/create-recipes.vue|174 col 28|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/create-recipes.vue#L174)   Missing space before opening brace                                            space-before-blocks
[app/javascript/components/recipes/new/search-ingredient-list.vue|4 col 7|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L4) Disallow self-closing on HTML void elements (<input/>)                       vue/html-self-closing
[app/javascript/components/recipes/new/search-ingredient-list.vue|38 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L38) Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|39 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L39) Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|39 col 25|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L39)   Trailing spaces not allowed                                                  no-trailing-spaces
[app/javascript/components/recipes/new/search-ingredient-list.vue|40 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L40) Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|40 col 23|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L40) Expected to be enclosed by double quotes                                     vue/html-quotes
[app/javascript/components/recipes/new/search-ingredient-list.vue|41 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L41) Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|42 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L42) Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|43 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L43) Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent
[app/javascript/components/recipes/new/search-ingredient-list.vue|52 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L52)   Expected 1 empty line after import statement not followed by another import  import/newline-after-import
[app/javascript/components/recipes/new/search-ingredient-list.vue|56 col 49|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L56)   Missing trailing comma                                                       comma-dangle
[app/javascript/components/recipes/new/search-ingredient-list.vue|60 col 7|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L60)   Identifier 'current_page' is not in camel case                               camelcase
[app/javascript/components/recipes/new/search-ingredient-list.vue|61 col 44|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L61)   Missing trailing comma                                                       comma-dangle
[app/javascript/components/recipes/new/search-ingredient-list.vue|62 col 6|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L62)   Missing semicolon                                                            semi
[app/javascript/components/recipes/new/search-ingredient-list.vue|69 col 2|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/search-ingredient-list.vue#L69)   Missing semicolon                                                            semi
[app/javascript/components/recipes/new/selected-ingredients.vue|4 col 9|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/selected-ingredients.vue#L4)   Trailing spaces not allowed                            no-trailing-spaces
[app/javascript/components/recipes/new/selected-ingredients.vue|5 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/selected-ingredients.vue#L5) Expected indentation of 6 spaces but found 4 spaces    vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|14 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/selected-ingredients.vue#L14) Expected indentation of 8 spaces but found 7 spaces    vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|17 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/selected-ingredients.vue#L17) Expected indentation of 10 spaces but found 14 spaces  vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|18 col 1|](http://github.com/platanus/2021-1-Grupo4-Web/blob/14da3b4d0034f6efb6b54ff7a744451833fbd444/app/javascript/components/recipes/new/selected-ingredients.vue#L18) Expected indentation of 10 spaces but found 14 spaces  vue/html-indent
[app/javascript/components/recipes/new/selected-ingredients.vue|19 col 1|](ht [...]

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    +
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Trailing spaces not allowed                    no-trailing-spaces

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>A space is required after '{'                  object-curly-spacing

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing space before value for key 'required'  key-spacing

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>A space is required before '}'                 object-curly-spacing

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    object: {type: Object, required:true}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma                         comma-dangle

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon                              semi

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon                              semi

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          <search-ingredient-list
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        <selected-ingredients
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        />
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                   no-trailing-spaces

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    </base-modal>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</div>`), but 2 line breaks found  vue/multiline-html-element-content-newline

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +import { getIngredients, postIngredient, deleteIngredient, editIngredient } from './../../../api/ingredients.js';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  'postIngredient' is defined but never used                                    no-unused-vars

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +import { getIngredients, postIngredient, deleteIngredient, editIngredient } from './../../../api/ingredients.js';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  'deleteIngredient' is defined but never used                                  no-unused-vars

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +import { getIngredients, postIngredient, deleteIngredient, editIngredient } from './../../../api/ingredients.js';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  'editIngredient' is defined but never used                                    no-unused-vars

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    BaseModalComponent,
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  The "BaseModalComponent" component has been registered but not used           vue/no-unused-components

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +      my_ingredients: [],
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Identifier 'my_ingredients' is not in camel case                              camelcase

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                             semi

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +      this.my_ingredients = response.data.data.map((element) => ({
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Identifier 'my_ingredients' is not in camel case                              camelcase

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    toggleAddIngredientModal(){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredient(object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +      var i;
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Unexpected var, use let or const instead                                      no-var

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        if (this.selectedIngredients[i] == object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected '===' and instead saw '=='                                           eqeqeq

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        if (this.selectedIngredients[i] == object){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    addIngredientstoRecipe(){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        var existent = false;
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Unexpected var, use let or const instead                                      no-var

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        this.ingredients.forEach(existent_ingredient =>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Identifier 'existent_ingredient' is not in camel case                         camelcase

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        this.ingredients.forEach(existent_ingredient =>{
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space after =>                                                        arrow-spacing

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          if (ingredient.id == JSON.parse(existent_ingredient)["id"]){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected '===' and instead saw '=='                                           eqeqeq

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          if (ingredient.id == JSON.parse(existent_ingredient)["id"]){
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>["id"] is better written in dot notation                                      dot-notation

2021-05-27 02:27 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          if (ingredient.id == JSON.parse(existent_ingredient)["id"]){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Strings must use singlequote                                                  quotes

2021-05-27 02:35 UTC, monkeyci reviewed
Remaining comments which cannot be posted as a review comment to avoid GitHub Rate Limit

<details>
<summary>eslint</summary>

[app/javascript/packs/application.js|51 col 15|](http://github.com/platanus/2021-1-Grupo4-Web/blob/5ea863864b2d0266373748f2275859c5e5db8fc7/app/javascript/packs/application.js#L51) Property name "addButtonComponent" is not PascalCase  vue/component-definition-name-casing
</details>

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon  semi

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon  semi

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +          if (ingredient.id === JSON.parse(existentIngredient).id){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +            return;// este return es equivalente a un continue dentro del foreach
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected newline before return statement                                      newline-before-return

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +        if (existent){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/create-recipes.vue
> +    deleteIngredient(index){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                                            space-before-blocks

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      <input
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Disallow self-closing on HTML void elements (<input/>)                       vue/html-self-closing

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +           <p class="content-center text-center ml-2 font-semibold">
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             <add-button
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             <add-button
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                  no-trailing-spaces

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              :object=ingredient
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              :object=ingredient
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected to be enclosed by double quotes                                     vue/html-quotes

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +              @add-ingredient="addIngredient"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 16 spaces but found 14 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +             />
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 14 spaces but found 13 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +           </p>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 12 spaces but found 11 spaces                        vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +import addButton from './add-button.vue';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Expected 1 empty line after import statement not followed by another import  import/newline-after-import

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +    ingredients: { type: Array, required: true }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                       comma-dangle

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      current_page: 0,
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Identifier 'current_page' is not in camel case                               camelcase

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      header: ['name', 'price', 'quantity']
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                                       comma-dangle

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                            semi

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                                            semi

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    <div
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                            no-trailing-spaces

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    class="flex p-4 grid grid-cols-2 items-center justify-between "
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 6 spaces but found 4 spaces    vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +       @click="deleteIngredient(index)"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 7 spaces    vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +              class="w-4 h-4"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 10 spaces but found 14 spaces  vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +              src="../../../../assets/images/cancel-svg.svg"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 10 spaces but found 14 spaces  vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +            >
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 12 spaces   vue/html-indent

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    deleteIngredient(index){
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing space before opening brace                     space-before-blocks

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +    }
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing trailing comma                                 comma-dangle

2021-05-27 02:35 UTC, monkeyci commented on app/javascript/components/recipes/new/selected-ingredients.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                                      semi

2021-05-27 02:48 UTC, MariaJosefinaAlliende reviewed
Si usas VSCode te recomiendo usar el plugin ErrorLens para ver los warnings del linter en el editor mientras escribes....  Cuando hayas arreglado los warnings de mono 🐵  lo vuelvo a ver 😄

2021-05-27 02:48 UTC, MariaJosefinaAlliende commented on app/javascript/components/recipes/new/create-recipes.vue
> +            :ingredients="my_ingredients"
En ruby ocupamos snake_case, pero en js camelCase... así que lo cambiaría a `myIngredients`

2021-05-27 02:48 UTC, MariaJosefinaAlliende commented on app/javascript/components/recipes/new/create-recipes.vue
> +      my_ingredients: [],
Lo mismo, `myIngredients`

2021-05-27 02:52 UTC, miortiz1 commented on app/javascript/components/recipes/new/create-recipes.vue
> +            :ingredients="my_ingredients"
Okay! Graciaass, estaba revisando ahora lo del mono :sweat_smile: Tambien me alegó por eso, intalare lo que me recomendaste y lo arreglo al tiro

2021-05-27 03:04 UTC, monkeyci commented on app/javascript/components/recipes/new/search-ingredient-list.vue
> +      <input
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Disallow self-closing on HTML void elements (<input/>)  vue/html-self-closing

2021-05-27 03:04 UTC, monkeyci commented on app/javascript/packs/application.js
> +Vue.component('addButtonComponent', addButtonComponent);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Property name "addButtonComponent" is not PascalCase  vue/component-definition-name-casing

2021-05-27 03:18 UTC, monkeyci commented on app/javascript/packs/application.js
> +Vue.component('addButtonComponent', addButton);
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Property name "addButtonComponent" is not PascalCase  vue/component-definition-name-casing

2021-05-27 14:56 UTC, sofiadelano commented on app/javascript/components/recipes/new/add-button.vue
> +    +
Yo creo que quedaría mejor si se agrega un ícono con esa forma, más que poner el signo +. Y también lo centraría adentro del botón. Para eso existe un icon de heroicons que se llama plus

2021-05-27 14:56 UTC, sofiadelano commented on app/javascript/packs/application.js
> +import AddButton from '../components/recipes/new/add-button.vue';
Por lo que revisé, muchas de esas componentes las usas en un solo lugar, y en ese caso, la deberías importar solo en ese lugar, y no de manera global en application.js

2021-05-27 15:15 UTC, ValentinaAlvarezG requested changes
Ahí te dejé un par de comentarios con cosas por cambiar. Además, creo que seía bueno agregar un mensaje (tenemos algo como esto en otro lados) en caso de que el usuario no tenga ingredientes, en vez de que se vea el header de la tabla (onda if tiene ingredientes, mostrar la tabla entera, else no mostrar la tabla y mostrar el mensaje)

![image](https://user-images.githubusercontent.com/26123660/119852361-3b7c8c00-bedd-11eb-8357-f0c8b9766e97.png)

2021-05-27 15:15 UTC, ValentinaAlvarezG commented on app/javascript/components/recipes/new/container.vue
> +    element: { type: String, default: () => ('') },
Por qué es un string y no un object?

2021-05-27 15:15 UTC, ValentinaAlvarezG commented on app/views/recipes/new.html.erb
>            {"name": "Manzana","price": 1000, "quantity": 1.5, "measure": "Kg"}.to_json,
es mi idea o esto ya no debería estar?

2021-05-27 15:15 UTC, ValentinaAlvarezG commented on app/javascript/packs/application.js
> +Vue.component('AddButton', AddButton);
Como dijo la sofi creo que `SelectedIngredients` y `SearchedIngredientsList` deberías importarlas solo donde las usas, no aquí de forma global. Además, por lo que vi antes del botón de agregar (que creo es el que tiene el signo +) no es necesario hacerlo componente, basta con que agregues la parte del ` <button> .... </button>` a la componente que lo usa (por lo que nos dijeron de no hacer  tantas componentes si no iban a tener algún comportamiento o data).

2021-05-27 19:48 UTC, monkeyci commented on app/javascript/locales/es.js
> +      selected: 'Ingredientes seleccionados'
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing trailing comma  comma-dangle

2021-05-27 21:31 UTC, miortiz1 commented on app/javascript/packs/application.js
> +import AddButton from '../components/recipes/new/add-button.vue';
Done

2021-05-27 21:33 UTC, miortiz1 commented on app/javascript/packs/application.js
> +Vue.component('AddButton', AddButton);
done

2021-05-27 21:47 UTC, miortiz1 commented on app/views/recipes/new.html.erb
>            {"name": "Manzana","price": 1000, "quantity": 1.5, "measure": "Kg"}.to_json,
done

2021-05-27 21:47 UTC, miortiz1 commented on app/javascript/components/recipes/new/container.vue
> +    element: { type: String, default: () => ('') },
done

2021-05-29 15:03 UTC, ValentinaAlvarezG approved these changes
Bacán!

2021-05-29 20:24 UTC, sofiadelano approved these changes

2021-05-31 13:06 UTC, MariaJosefinaAlliende approved these changes
Perdón la demora!! Se me había olvidado por completo este PR 😞 . Aprobado!! ✅   Ojo si que hay merge conflicts 👀  para que los resuelvas antes del merge

2021-05-31 17:44 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> + <template>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 0 spaces but found 1 space                                vue/html-indent

2021-05-31 17:44 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> + <template>
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Trailing spaces not allowed                                                       no-trailing-spaces

2021-05-31 17:44 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +      @click="clickButton"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 4 spaces but found 6 spaces                               vue/html-indent

2021-05-31 17:44 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +  > + </button>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break after opening tag (`<button>`), but no line breaks found    vue/multiline-html-element-content-newline

2021-05-31 17:44 UTC, monkeyci commented on app/javascript/components/recipes/new/add-button.vue
> +  > + </button>
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 line break before closing tag (`</button>`), but no line breaks found  vue/multiline-html-element-content-newline

2021-06-01 18:15 UTC, merged