feat(filters): ready portions filter
platanus/2021-1-Grupo4-Web pull request #73
Opened 2021-06-01 16:48 UTC by Arodriguez14

### Lo que se hizo ### 

Se creo el filtro de recetas en cuanto a la cantidad de porciones

### Falta ### 
Falta crear el filtro de recetas en cuanto a precio. No lo hice porque todavia las recetas no tienen precios porque no se puede agregar ingredientes (eso está en PR y cuando lo acepten voy a terminar esto).

### QA ### 
Ir a la rama filters y correr la app. Luego ir a /recipes. Ahí podrán crear un par de recetas y luego filtrar por la cantidad de porciones y ver como aparecen las recetas que están dentro del rango de porciones del filtro. Además se puede borrar el filtro.

2021-06-01 18:24 UTC, fncabrera reviewed
Esta perfect en QA, pero un comentario: creo que sería bueno en el modal del filtro, que aparezca el filtro actual en el input (si es que hay un filtro puesto). Por ej, si hay un filtro de menor a 3, que aparezca así:
![image](https://user-images.githubusercontent.com/30879712/120372347-1628bd00-c2e5-11eb-9071-73cefb9496ae.png)

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +    console.log("actuales",this.actualfilters)
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement             no-console

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +    console.log("actuales",this.actualfilters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Strings must use singlequote             quotes

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +    console.log("actuales",this.actualfilters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  A space is required after ','            comma-spacing

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +    console.log("actuales",this.actualfilters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Block must not be padded by blank lines  padded-blocks

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +    console.log("actuales",this.actualfilters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon                        semi

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-container.vue
> +      console.log("back", this.filters)
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement  no-console

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-container.vue
> +      console.log("back", this.filters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Strings must use singlequote  quotes

2021-06-02 19:32 UTC, monkeyci commented on app/javascript/components/recipes/index/recipes-container.vue
> +      console.log("back", this.filters)
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>  Missing semicolon             semi

2021-06-02 19:54 UTC, ValentinaAlvarezG reviewed
Super bien!  pídeme revisar de nuevo cuando arregles los problemas del mono y cuando agregues los cambios que te pidió Pipe.

 Lo que si, creo que hace falta una manera de quitar los filtros, porque actualmente no hay una forma y creo que igual es importante (no sé si hay algo explícito por parte de platanus en los figma tanto en UX como UI, pero hacer algo lo más intuitivo posible, quizás se puede hablar por slack con el equipo).

2021-06-02 21:22 UTC, rjherrera requested changes
me sumo a lo de arreglar los comentarios de linting jaja, te dejé un par de sugerencias!

2021-06-02 21:22 UTC, rjherrera commented on app/javascript/components/recipes/index/filter-popup-content.vue
> +        id="portionsmax"
este id lo necesitas para algo? creo que lo sacaría si no se usa

2021-06-02 21:22 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.recipesShow = this.recipesFiltered;
esto lo podrías hacer con un filter y con un and, en general en javascript se intenta evitar usar fors directos a menos que sea estrictamente necesario, queda más legible usando filter, map, forEach, find, etc:
```js
this.recipesAll.filter(
  recipe => recipe.portions >= this.filters.portions.min && recipe.portions <= this.filters.portions.max,
);
```

2021-06-02 21:22 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.updateRecipes();
creo que no deberías usar un método que haga el update a mano. En vez de eso deberías tener un computed, no sé si los conoces, pero así como esta función está dentro de la llave `methods` hay otra llave que se llama `computed` en la que puedes meter métodos sin parámetros.

Con eso definirías algo como `filteredRecipes` que revisa los filtros usando filter, map, o lo que corresponda y siempre entrega el arreglo filtrado, con eso te despreocupas de mantener 3 arreglos, el show el all y el filtered. Simplemente obtienes las recetas y las guardas en 1 arreglo, y después defines tu método que retorna las recetas filtradas. Los computed son inteligentes y cuando cambia algo que se usa para el cálculo de ese método, se actualiza el retorno de ese método.

Me imagino algo como:
```js
computed: {
  filteredRecipes() {
    return this.recipes.filter(...);
  }
}
```

y llamarlo en el html como `:allrecipes="filteredRecipes"`

Si tu lógica es más complicada que un solo filtro, igual se puede manejar dentro del método computed de filtered recipes, puedes definir variables y lo que quieras dentro

2021-06-05 13:19 UTC, Arodriguez14 commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.updateRecipes();
Perfect!! Muchas gracias por los comentarios. Voy a hacer rebase de master para agregar los filtros de los precios también y cuando esté todo listo vuelvo a avisarte. Se entiende perfect la idea! Queda mucho mas claro!!

Gracias!

2021-06-06 15:04 UTC, Arodriguez14 commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.updateRecipes();
Ahí arregle los comentarios! Los detalles de diseño los dejaré para la próxima PR, pero ya está todo funcional!! Quedo atento a comentarios!! @ValentinaAlvarezG @rjherrera 

Muchas gracias!!

2021-06-07 12:45 UTC, ValentinaAlvarezG approved these changes
Se ve super!

2021-06-07 14:53 UTC, rjherrera reviewed
buena mejoró harto! te dejé un par de comentarios más pero va en el buen camino!

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/filters.vue
> +    </div> -->
en general evitamos dejar código comentado porque después no se sabe si se puede borrar o no y genera código inútil en los repos. Aparte por lo que veo es algo nuevo que no se usaba o sí?

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/filters.vue
> +  },
por lo que veo ninguno de los dos se usa, son necesarios? Creo que además de sacarlos, si se usaran, no sería la mejor solución hacerlo así a menos que sea un caso borde que solo se da al inicio del componente

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +    // },
no olvides sacar estos comentarios

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +    // eslint-disable-next-line complexity
en general si nos está alegando por esto es porque efectivamente nuestro método está muy complejo, encuentro que cuesta mucho entenderlo, trataría de no sacar las reglas así en estos casos en los que efectivamente está evidenciando una característica mejorable del código

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +            recipePrice + this.getPriceOfSelectedIngredient(recipeIngredient.attributes), 0) >=
si bien es bueno que usemos los every y los filter, creo que la parte de la lógica que es repetible es bueno tratar de dejarla modularizada. En este caso la parte de

```js
recipe.recipeIngredients.data.reduce((recipePrice, recipeIngredient) =>
          recipePrice + this.getPriceOfSelectedIngredient(recipeIngredient.attributes), 0)
```
está repetida muchas veces y hace que sea muy difícil entender el código. Quizás con un método que recibe un ingrediente y retorna el resultado del reduce se mejora bastante esto

2021-06-07 14:53 UTC, rjherrera commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.updateFiltersToCompare();
trataría de evitar este método. Si te fijai lo que haces en ese método es cambiar de '' a valores en los casos en los que es necesario. Eso podría ser un computed `filtersToCompare` que te retornara un objeto con los filtros en el formato que quieres, sin tener que editar variables reales de tu componente

2021-06-08 02:15 UTC, Arodriguez14 commented on app/javascript/components/recipes/index/recipes-container.vue
> +    // },
Perdón! Mala mia, debí haber revisado el codigo antes de subirlo

2021-06-08 02:15 UTC, Arodriguez14 commented on app/javascript/components/recipes/index/recipes-container.vue
> +            recipePrice + this.getPriceOfSelectedIngredient(recipeIngredient.attributes), 0) >=
Perfect! Se entiende perfecto la idea. Ahi lo implemente y es verdad que ahora está mas claro. Gracias por el comentario!

2021-06-08 02:16 UTC, Arodriguez14 commented on app/javascript/components/recipes/index/recipes-container.vue
> +      this.updateFiltersToCompare();
Toda la razón! Mucho mejor no editar variables reales. Ya está corregido! Muchas gracias raimundo!!

2021-06-08 02:17 UTC, Arodriguez14 commented
@rjherrera ya arreglé todos los comentarios que me hiciste! Creo que me sirvieron mucho para aprender mejores prácticas. Muchísimas gracias!! Quedo atento!

2021-06-08 02:34 UTC, rjherrera approved these changes
buenísimo! bacán que te hayan servido los comentarios, y sorry lo latero jaja, quedó mucho mejor!

2021-06-08 02:35 UTC, Arodriguez14 commented
> buenísimo! bacán que te hayan servido los comentarios, y sorry lo latero jaja, quedó mucho mejor!

Jajajaj nada de latero! Quedó mucho mas claro y sirve para aprender. Gracias!

2021-06-08 02:36 UTC, merged