feat(frontend/create-recipe): add delete ingredient on create recipe)
platanus/2021-1-Grupo4-Web pull request #79
Opened 2021-06-03 18:41 UTC by miortiz1

# Que se hizo
Se pueden borrar ingredientes ya añadidos en crear recetas
# QA
Al añadir un ingrediente, al apretar "x" se elimina y se puede añadir de nuevo

2021-06-03 18:42 UTC, monkeyci commented on app/javascript/components/recipes/new/list.vue
> +      this.elements.splice(index, 1);
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected mutation of "elements" prop  vue/no-mutating-props

2021-06-03 18:58 UTC, iaacosta requested changes

2021-06-03 18:58 UTC, iaacosta commented on app/javascript/components/recipes/new/list.vue
> +      ingredients: this.elements,
Clonaría el arreglo, creo que pueden aparecer warnings y comportamientos raros si usamos el mismo objeto en el data que en la prop:

```suggestion
      ingredients: [...this.elements],
```

2021-06-03 18:58 UTC, iaacosta commented on app/javascript/components/recipes/new/list.vue
> +    },
Lo mejor acá es reemplazar completamente el arreglo en lugar de forzar el update, tratamos de no hacerlo. Yo generalmente lo hago a través de un `filter`, así:

```suggestion
    delIngredient(ingredient) {
      this.ingredients = this.ingredients.filter((originalIngredient) => originalIngredient.id !== ingredient.id);
    },
```

Arriba también veo que se usa harto 😢  trataría de hacer un refactor en un futuro. Cuéntame qué te parece

2021-06-04 06:30 UTC, miortiz1 commented on app/javascript/components/recipes/new/list.vue
> +    },
Entiendo perfecto! No creo que se use taanto, asi que deberia salir bien rapido el refactor! :) graciass

2021-06-04 06:31 UTC, miortiz1 commented on app/javascript/components/recipes/new/list.vue
> +      ingredients: this.elements,
Entiendo perfecto, lo arregle de otra forma, porque entendi que estaba mal tenerlo en data y modificarlo ahi. Al final termine mandando un emit para que se modifique la data del padre

2021-06-04 11:22 UTC, iaacosta commented on app/javascript/components/recipes/new/list.vue
> +      ingredients: this.elements,
Buena! Mucho mejor, quedo bacán 💯

2021-06-04 11:23 UTC, iaacosta approved these changes

2021-06-04 15:28 UTC, aescobar4 approved these changes
Esta perfect!

2021-06-04 15:36 UTC, merged