feat(web): add close events of modals
platanus/2021-1-Grupo4-Web pull request #92
Opened 2021-06-10 20:47 UTC by cacosandon

Agrego eventos para cerrar el modal grande y los dots dropdown!

https://user-images.githubusercontent.com/30879716/121594701-6dc4d800-ca0b-11eb-89ad-53410a39794c.mov

https://user-images.githubusercontent.com/30879716/121594709-70273200-ca0b-11eb-8d0e-9ea79e368a1f.mov

2021-06-10 21:09 UTC, sofiadelano approved these changes
Esta perfecto!!

2021-06-11 14:29 UTC, agomezcampero requested changes
Para los modales no usaron https://github.com/euvl/vue-js-modal? 

Me parece bien en todo caso la manera que lo están manejando pero creo que sería bueno hacer el [removeEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) para no estar acumulando eventListeners

2021-06-12 16:01 UTC, cacosandon commented
> Para los modales no usaron https://github.com/euvl/vue-js-modal?
> 
> Me parece bien en todo caso la manera que lo están manejando pero creo que sería bueno hacer el [removeEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) en el `unmounted` para no estar acumulando eventListeners

parece que no lo usamos! acabo de agregar el remove listeners

2021-06-14 13:18 UTC, agomezcampero commented on app/javascript/components/base/dots-dropdown.vue
> +    document.removeEventListener('click');
Acá tienes que pasarle la función tbn
```suggestion
    document.removeEventListener('click', this.closeDropdown);
```

2021-06-14 21:28 UTC, cacosandon commented on app/javascript/components/base/dots-dropdown.vue
> +    document.removeEventListener('click');
oops

2021-06-15 00:42 UTC, agomezcampero approved these changes

2021-06-15 00:59 UTC, merged